# 8.1 Hierarchical Indexing

In [2]:
import numpy as np
import pandas as pd

In [3]:
data=pd.Series(np.random.uniform(size=9),
               index=[['a','a','a','b','b','c','c','d','d'],
                      [1,2,3,1,3,1,2,2,3]])

In [4]:
data

a  1    0.385607
   2    0.256063
   3    0.027331
b  1    0.424431
   3    0.720308
c  1    0.337676
   2    0.079699
d  2    0.588203
   3    0.819898
dtype: float64

In [5]:
data.index

MultiIndex([('a', 1),
            ('a', 2),
            ('a', 3),
            ('b', 1),
            ('b', 3),
            ('c', 1),
            ('c', 2),
            ('d', 2),
            ('d', 3)],
           )

In [6]:
data["b"]

1    0.424431
3    0.720308
dtype: float64

In [7]:
data["b":"c"]

b  1    0.424431
   3    0.720308
c  1    0.337676
   2    0.079699
dtype: float64

In [8]:
data.loc[["b","d"]]

b  1    0.424431
   3    0.720308
d  2    0.588203
   3    0.819898
dtype: float64

In [9]:
data.loc[:,2]

a    0.256063
c    0.079699
d    0.588203
dtype: float64

In [10]:
pd.DataFrame(data)

            0
a 1  0.385607
  2  0.256063
  3  0.027331
b 1  0.424431
  3  0.720308
c 1  0.337676
  2  0.079699
d 2  0.588203
  3  0.819898

In [11]:
data.unstack()

          1         2         3
a  0.385607  0.256063  0.027331
b  0.424431       NaN  0.720308
c  0.337676  0.079699       NaN
d       NaN  0.588203  0.819898

In [12]:
data.unstack().stack()

a  1    0.385607
   2    0.256063
   3    0.027331
b  1    0.424431
   3    0.720308
c  1    0.337676
   2    0.079699
d  2    0.588203
   3    0.819898
dtype: float64

In [13]:
frame=pd.DataFrame(np.arange(12).reshape((4,3)),
                   index=[["a","a","b","b"],
                          [1,2,1,2]],
                   columns=[["Ohio","Ohio","Colorado"],
                            ["Green","Red","Green"]])

In [14]:
frame

     Ohio     Colorado
    Green Red    Green
a 1     0   1        2
  2     3   4        5
b 1     6   7        8
  2     9  10       11

In [15]:
frame.index.names=["key1","key2"]

In [16]:
frame.columns.names=["state","color"]

In [17]:
frame

state      Ohio     Colorado
color     Green Red    Green
key1 key2
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

In [18]:
frame.index.nlevels

2

In [19]:
frame["Ohio"]

color      Green  Red
key1 key2
a    1         0    1
     2         3    4
b    1         6    7
     2         9   10

In [20]:
pd.MultiIndex.from_arrays(
    [["Ohio","Ohio","Colorado"],
     ["Green","Red","Green"]],
    names=["state","color"]
)

MultiIndex([(    'Ohio', 'Green'),
            (    'Ohio',   'Red'),
            ('Colorado', 'Green')],
           names=['state', 'color'])

Reordering and Sorting Levels

In [21]:
frame.swaplevel("key1","key2")

state      Ohio     Colorado
color     Green Red    Green
key2 key1
1    a        0   1        2
2    a        3   4        5
1    b        6   7        8
2    b        9  10       11

In [22]:
frame.sort_index(level=1)

state      Ohio     Colorado
color     Green Red    Green
key1 key2
a    1        0   1        2
b    1        6   7        8
a    2        3   4        5
b    2        9  10       11

In [23]:
frame.swaplevel(0,1).sort_index(level=0)

state      Ohio     Colorado
color     Green Red    Green
key2 key1
1    a        0   1        2
     b        6   7        8
2    a        3   4        5
     b        9  10       11

Summary Statistics by Level

In [24]:
frame.groupby(level="key2").sum()

state  Ohio     Colorado
color Green Red    Green
key2
1         6   8       10
2        12  14       16

In [25]:
frame

state      Ohio     Colorado
color     Green Red    Green
key1 key2
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

In [26]:
frame.groupby(level="color",axis="columns").sum()

C:\Users\Prathamesh Gawas\AppData\Local\Temp\ipykernel_11644\3295922660.py:1: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  frame.groupby(level="color",axis="columns").sum()

color      Green  Red
key1 key2
a    1         2    1
     2         8    4
b    1        14    7
     2        20   10

Indexing with a DataFrame’s columns

In [27]:
frame = pd.DataFrame({"a": range(7), "b": range(7, 0, -1),
                         "c": ["one", "one", "one", "two", "two",
                           "two", "two"],
                      "d": [0, 1, 2, 0, 1, 2, 3]})

In [28]:
frame

   a  b    c  d
0  0  7  one  0
1  1  6  one  1
2  2  5  one  2
3  3  4  two  0
4  4  3  two  1
5  5  2  two  2
6  6  1  two  3

In [29]:
frame2=frame.set_index(["c","d"])

In [30]:
frame2

       a  b
c   d
one 0  0  7
    1  1  6
    2  2  5
two 0  3  4
    1  4  3
    2  5  2
    3  6  1

In [31]:
frame.set_index(["c","d"],drop=False)

       a  b    c  d
c   d
one 0  0  7  one  0
    1  1  6  one  1
    2  2  5  one  2
two 0  3  4  two  0
    1  4  3  two  1
    2  5  2  two  2
    3  6  1  two  3

In [32]:
frame2.reset_index()

     c  d  a  b
0  one  0  0  7
1  one  1  1  6
2  one  2  2  5
3  two  0  3  4
4  two  1  4  3
5  two  2  5  2
6  two  3  6  1

# 8.2 Combining and Merging Datasets

In [33]:
df1 = pd.DataFrame({"key": ["b", "b", "a", "c", "a", "a", "b"],               
"data1": pd.Series(range(7), dtype="Int64")})

In [34]:
df2 = pd.DataFrame({"key": ["a", "b", "d"],                   
"data2": pd.Series(range(3), dtype="Int64")})

In [35]:
df1

  key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   a      5
6   b      6

In [36]:
df2

  key  data2
0   a      0
1   b      1
2   d      2

In [37]:
print(df1)
print(df2)

  key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   a      5
6   b      6
  key  data2
0   a      0
1   b      1
2   d      2

In [38]:
pd.merge(df1,df2)

  key  data1  data2
0   b      0      1
1   b      1      1
2   a      2      0
3   a      4      0
4   a      5      0
5   b      6      1

In [39]:
pd.merge(df1,df2,on="key")

  key  data1  data2
0   b      0      1
1   b      1      1
2   a      2      0
3   a      4      0
4   a      5      0
5   b      6      1

In [40]:
df3 = pd.DataFrame({"lkey": ["b", "b", "a", "c", "a", "a", "b"],
                   "data1": pd.Series(range(7), dtype="Int64")})

In [41]:
df4 = pd.DataFrame({"rkey": ["a", "b", "d"],
                     "data2": pd.Series(range(3), dtype="Int64")})

In [42]:
df3

  lkey  data1
0    b      0
1    b      1
2    a      2
3    c      3
4    a      4
5    a      5
6    b      6

In [43]:
df4

  rkey  data2
0    a      0
1    b      1
2    d      2

In [44]:
print(df3)
print(df4)

  lkey  data1
0    b      0
1    b      1
2    a      2
3    c      3
4    a      4
5    a      5
6    b      6
  rkey  data2
0    a      0
1    b      1
2    d      2

In [45]:
pd.merge(df3,df4,left_on="lkey",right_on="rkey")

  lkey  data1 rkey  data2
0    b      0    b      1
1    b      1    b      1
2    a      2    a      0
3    a      4    a      0
4    a      5    a      0
5    b      6    b      1

In [46]:
print(df1)
print(df2)

  key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   a      5
6   b      6
  key  data2
0   a      0
1   b      1
2   d      2

In [47]:
pd.merge(df1,df2,how="outer")

  key  data1  data2
0   a      2      0
1   a      4      0
2   a      5      0
3   b      0      1
4   b      1      1
5   b      6      1
6   c      3   <NA>
7   d   <NA>      2

In [48]:
pd.merge(df3,df4,left_on="lkey",right_on="rkey",how="outer")

  lkey  data1 rkey  data2
0    a      2    a      0
1    a      4    a      0
2    a      5    a      0
3    b      0    b      1
4    b      1    b      1
5    b      6    b      1
6    c      3  NaN   <NA>
7  NaN   <NA>    d      2

## Table 8-1. Different join types with the `how` argument

| Option        | Behavior                                                        | Example (Python) | Result |
|---------------|-----------------------------------------------------------------|------------------|--------|
| `how="inner"` | Use only the key combinations observed in both tables           | `pd.merge(df1, df2, how="inner", on="key")` | Intersection of keys |
| `how="left"`  | Use all key combinations found in the left table                 | `pd.merge(df1, df2, how="left", on="key")`  | All keys from left, match from right |
| `how="right"` | Use all key combinations found in the right table                | `pd.merge(df1, df2, how="right", on="key")` | All keys from right, match from left |
| `how="outer"` | Use all key combinations observed in both tables together        | `pd.merge(df1, df2, how="outer", on="key")` | Union of keys |

In [49]:
df1=pd.DataFrame({
    "key":list("bbacab"),
    "data1":pd.Series(range(6),dtype="Int64")
})

In [50]:
df2=pd.DataFrame({
    "key":list("ababd"),
    "data2":pd.Series(range(5),dtype="Int64")
})

In [51]:
df1

  key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [52]:
df2

  key  data2
0   a      0
1   b      1
2   a      2
3   b      3
4   d      4

In [53]:
pd.merge(df1,df2,on="key",how="left")

   key  data1  data2
0    b      0      1
1    b      0      3
2    b      1      1
3    b      1      3
4    a      2      0
5    a      2      2
6    c      3   <NA>
7    a      4      0
8    a      4      2
9    b      5      1
10   b      5      3

In [54]:
pd.merge(df1,df2,how="inner")

  key  data1  data2
0   b      0      1
1   b      0      3
2   b      1      1
3   b      1      3
4   a      2      0
5   a      2      2
6   a      4      0
7   a      4      2
8   b      5      1
9   b      5      3

In [55]:
left = pd.DataFrame({"key1": ["foo", "foo", "bar"],
                    
"key2": ["one", "two", "one"],
"lval": pd.Series([1, 2, 3], dtype='Int64')})

In [56]:
right=pd.DataFrame({"key1": ["foo", "foo", "bar", "bar"],
                    "key2": ["one", "one", "one", "two"],
                   "rval": pd.Series([4, 5, 6, 7], dtype='Int64')})

In [57]:
left

  key1 key2  lval
0  foo  one     1
1  foo  two     2
2  bar  one     3

In [58]:
right

  key1 key2  rval
0  foo  one     4
1  foo  one     5
2  bar  one     6
3  bar  two     7

In [59]:
pd.merge(left,right,on=["key1","key2"],how="outer")

  key1 key2  lval  rval
0  bar  one     3     6
1  bar  two  <NA>     7
2  foo  one     1     4
3  foo  one     1     5
4  foo  two     2  <NA>

In [60]:
left

  key1 key2  lval
0  foo  one     1
1  foo  two     2
2  bar  one     3

In [61]:
right

  key1 key2  rval
0  foo  one     4
1  foo  one     5
2  bar  one     6
3  bar  two     7

In [62]:
pd.merge(left,right,on="key1")

  key1 key2_x  lval key2_y  rval
0  foo    one     1    one     4
1  foo    one     1    one     5
2  foo    two     2    one     4
3  foo    two     2    one     5
4  bar    one     3    one     6
5  bar    one     3    two     7

In [63]:
pd.merge(left,right,on="key1",suffixes=("_left","_right"))

  key1 key2_left  lval key2_right  rval
0  foo       one     1        one     4
1  foo       one     1        one     5
2  foo       two     2        one     4
3  foo       two     2        one     5
4  bar       one     3        one     6
5  bar       one     3        two     7

## Arguments for `pandas.merge`

| Argument      | Description                                                                 | Example (Python) |
|---------------|-----------------------------------------------------------------------------|------------------|
| `left`        | DataFrame to be merged on the left side                                     | `pd.merge(df1, df2, ...)` |
| `right`       | DataFrame to be merged on the right side                                    | `pd.merge(df1, df2, ...)` |
| `how`         | Type of join: `"inner"`, `"outer"`, `"left"`, `"right"`; defaults to `"inner"` | `pd.merge(df1, df2, how="outer")` |
| `on`          | Column names to join on; must exist in both DataFrames. If not specified, uses intersection of column names | `pd.merge(df1, df2, on="id")` |
| `left_on`     | Column(s) in left DataFrame to use as join keys                             | `pd.merge(df1, df2, left_on="id1", right_on="id2")` |
| `right_on`    | Column(s) in right DataFrame to use as join keys                            | Same as above |
| `left_index`  | Use row index in left as join key (supports MultiIndex)                     | `pd.merge(df1, df2, left_index=True, right_on="id")` |
| `right_index` | Use row index in right as join key                                          | `pd.merge(df1, df2, right_index=True, left_on="id")` |
| `sort`        | Sort merged data lexicographically by join keys; default `False`            | `pd.merge(df1, df2, on="id", sort=True)` |
| `suffixes`    | Tuple of suffixes for overlapping column names; default `("_x","_y")`       | `pd.merge(df1, df2, on="id", suffixes=("_left","_right"))` |
| `copy`        | If `False`, avoid copying data in some cases; default always copies         | `pd.merge(df1, df2, copy=False)` |
| `validate`    | Verifies merge type: `"1:1"`, `"1:m"`, `"m:1"`, `"m:m"`                     | `pd.merge(df1, df2, on="id", validate="1:1")` |
| `indicator`   | Adds `_merge` column showing source of each row: `"left_only"`, `"right_only"`, `"both"` | `pd.merge(df1, df2, on="id", indicator=True)` |

Merging on Index

In [64]:
left1=pd.DataFrame({
    "key":list("abaabc"),
    "value":pd.Series(range(6),dtype="Int64")
})

In [65]:
right1=pd.DataFrame({
    "group_val":[3.5,7]
},
                    index=["a","b"])

In [66]:
left1

  key  value
0   a      0
1   b      1
2   a      2
3   a      3
4   b      4
5   c      5

In [67]:
right1

   group_val
a        3.5
b        7.0

In [68]:
pd.merge(left1,right1,left_on="key",right_index=True)

  key  value  group_val
0   a      0        3.5
1   b      1        7.0
2   a      2        3.5
3   a      3        3.5
4   b      4        7.0

In [69]:
pd.merge(left1,right1,left_on="key",right_index=True,how="outer")

  key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0
5   c      5        NaN

In [70]:
lefth=pd.DataFrame({
    "key1":["Ohio","Ohio","Ohio","Nevada","Nevada"],
    "key2":[2000,2001,2002,2001,2002],
    "data1":pd.Series(np.arange(5),dtype="Int64")
})

In [73]:
righth_index = pd.MultiIndex.from_arrays(
   [["Nevada", "Nevada", "Ohio", "Ohio", "Ohio", "Ohio"],[2001, 2000, 2000, 2000, 2001, 2002]]
    )

In [74]:
righth=pd.DataFrame({
    "event1":pd.Series([0,2,4,6,8,10],dtype="Int64",index=righth_index),
    "event2":pd.Series([1,3,5,7,9,11],dtype="Int64",index=righth_index)
})

In [75]:
lefth

     key1  key2  data1
0    Ohio  2000      0
1    Ohio  2001      1
2    Ohio  2002      2
3  Nevada  2001      3
4  Nevada  2002      4

In [77]:
righth_index

MultiIndex([('Nevada', 2001),
            ('Nevada', 2000),
            (  'Ohio', 2000),
            (  'Ohio', 2000),
            (  'Ohio', 2001),
            (  'Ohio', 2002)],
           )

In [76]:
righth

             event1  event2
Nevada 2001       0       1
       2000       2       3
Ohio   2000       4       5
       2000       6       7
       2001       8       9
       2002      10      11

In [79]:
pd.merge(lefth,righth,left_on=["key1","key2"],right_index=True)

     key1  key2  data1  event1  event2
0    Ohio  2000      0       4       5
0    Ohio  2000      0       6       7
1    Ohio  2001      1       8       9
2    Ohio  2002      2      10      11
3  Nevada  2001      3       0       1

In [80]:
pd.merge(lefth,righth,left_on=["key1","key2"],right_index=True,how="outer")

     key1  key2  data1  event1  event2
4  Nevada  2000   <NA>       2       3
3  Nevada  2001      3       0       1
4  Nevada  2002      4    <NA>    <NA>
0    Ohio  2000      0       4       5
0    Ohio  2000      0       6       7
1    Ohio  2001      1       8       9
2    Ohio  2002      2      10      11

In [81]:
left2=pd.DataFrame([[1.,2.],[3.,4.],[5.,6.]],
                   index=["a","c","e"],
                   columns=["Ohio","Nevada"]).astype("Int64")

In [82]:
right2=pd.DataFrame([[7.,8.],[9.,10.],[11.,12.],[13.,14.]],
                   index=["a","c","e","f"],
                   columns=["Missouri","Alabama"]).astype("Int64")

In [83]:
left2

   Ohio  Nevada
a     1       2
c     3       4
e     5       6

In [84]:
right2

   Missouri  Alabama
a         7        8
c         9       10
e        11       12
f        13       14

In [91]:
pd.merge(left2,right2,how="outer",left_index=True,right_index=True)

   Ohio  Nevada  Missouri  Alabama
a     1       2         7        8
c     3       4         9       10
e     5       6        11       12
f  <NA>    <NA>        13       14

In [92]:
left2.join(right2,how="outer")

   Ohio  Nevada  Missouri  Alabama
a     1       2         7        8
c     3       4         9       10
e     5       6        11       12
f  <NA>    <NA>        13       14

In [93]:
left1.join(right1,on="key")

  key  value  group_val
0   a      0        3.5
1   b      1        7.0
2   a      2        3.5
3   a      3        3.5
4   b      4        7.0
5   c      5        NaN

In [ ]:
another = pd.DataFrame([[7., 8.], [9., 10.], [11., 12.], [16., 17.]],                   
                       index=["a", "c", "e", "f"],
                      columns=["New York", "Oregon"])

In [95]:
another

   New York  Oregon
a       7.0     8.0
c       9.0    10.0
e      11.0    12.0
f      16.0    17.0

In [96]:
left2.join([right2,another])

   Ohio  Nevada  Missouri  Alabama  New York  Oregon
a     1       2         7        8       7.0     8.0
c     3       4         9       10       9.0    10.0
e     5       6        11       12      11.0    12.0

In [97]:
left2.join([right2,another],how="outer")

   Ohio  Nevada  Missouri  Alabama  New York  Oregon
a     1       2         7        8       7.0     8.0
c     3       4         9       10       9.0    10.0
e     5       6        11       12      11.0    12.0
f  <NA>    <NA>        13       14      16.0    17.0

Concatenating Along an Axis

In [99]:
arr=np.arange(12).reshape((3,4))

In [100]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [101]:
np.concatenate([arr,arr],axis=1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [102]:
s1=pd.Series([0,1],index=["a","b"],dtype="Int64")

In [103]:
s2=pd.Series([2,3,4],index=["c","d","e"],dtype="Int64")

In [104]:
s3=pd.Series([5,6],index=["f","g"],dtype="Int64")

In [105]:
s1

a    0
b    1
dtype: Int64

In [106]:
s2

c    2
d    3
e    4
dtype: Int64

In [107]:
s3

f    5
g    6
dtype: Int64

In [108]:
pd.concat([s1,s2,s3])

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: Int64

In [109]:
pd.concat([s1,s2,s3],axis="columns")

      0     1     2
a     0  <NA>  <NA>
b     1  <NA>  <NA>
c  <NA>     2  <NA>
d  <NA>     3  <NA>
e  <NA>     4  <NA>
f  <NA>  <NA>     5
g  <NA>  <NA>     6

In [110]:
s4=pd.concat([s1,s3])

In [111]:
s4

a    0
b    1
f    5
g    6
dtype: Int64

In [112]:
pd.concat([s1,s4],axis="columns")

      0  1
a     0  0
b     1  1
f  <NA>  5
g  <NA>  6

In [114]:
s1

a    0
b    1
dtype: Int64

In [115]:
s4

a    0
b    1
f    5
g    6
dtype: Int64

In [113]:
pd.concat([s1,s4],axis="columns",join="inner")

   0  1
a  0  0
b  1  1

In [116]:
result=pd.concat([s1,s1,s3],keys=["one","two","three"])

In [117]:
result

one    a    0
       b    1
two    a    0
       b    1
three  f    5
       g    6
dtype: Int64

In [118]:
result.unstack()

          a     b     f     g
one       0     1  <NA>  <NA>
two       0     1  <NA>  <NA>
three  <NA>  <NA>     5     6

In [122]:
pd.concat([s1,s2,s3],axis="columns",keys=["one","two","three"])

    one   two  three
a     0  <NA>   <NA>
b     1  <NA>   <NA>
c  <NA>     2   <NA>
d  <NA>     3   <NA>
e  <NA>     4   <NA>
f  <NA>  <NA>      5
g  <NA>  <NA>      6

In [123]:
df1=pd.DataFrame(
    np.arange(6).reshape(3,2),
    index=["a","b","c"],
    columns=["one","two"]
)

In [124]:
df2=pd.DataFrame(
    5+np.arange(4).reshape(2,2),
    index=["a","c"],
    columns=["three","four"]
)

In [125]:
df1

   one  two
a    0    1
b    2    3
c    4    5

In [126]:
df2

   three  four
a      5     6
c      7     8

In [127]:
pd.concat([df1,df2],axis="columns",keys=["level1","level2"])

  level1     level2
     one two  three four
a      0   1    5.0  6.0
b      2   3    NaN  NaN
c      4   5    7.0  8.0

In [128]:
pd.concat({
    "level1":df1,
    "level2":df2
},
          axis="columns")

  level1     level2
     one two  three four
a      0   1    5.0  6.0
b      2   3    NaN  NaN
c      4   5    7.0  8.0

In [129]:
pd.concat([df1,df2],axis="columns",keys=["level1","level2"],names=["upper","lower"])

upper level1     level2
lower    one two  three four
a          0   1    5.0  6.0
b          2   3    NaN  NaN
c          4   5    7.0  8.0

In [141]:
df1=pd.DataFrame(np.random.standard_normal((3,4)),
                 columns=list("abcd"))

In [142]:
df2=pd.DataFrame(np.random.standard_normal((2,3)),
                 columns=list("bda"))

In [143]:
df1

          a         b         c         d
0  0.474810 -0.759756 -1.195274 -1.206152
1 -0.264535 -0.812427 -0.598842 -0.797966
2 -0.826909 -0.979850  1.255759  0.696079

In [144]:
df2

          b         d         a
0 -0.129590 -0.282257  0.085885
1  0.040934  1.257567 -0.989909

In [145]:
pd.concat([df1,df2],ignore_index=True)

          a         b         c         d
0  0.474810 -0.759756 -1.195274 -1.206152
1 -0.264535 -0.812427 -0.598842 -0.797966
2 -0.826909 -0.979850  1.255759  0.696079
3  0.085885 -0.129590       NaN -0.282257
4 -0.989909  0.040934       NaN  1.257567

## Arguments for `pandas.concat`

| Argument          | Description                                                                 | Example (Python) |
|-------------------|-----------------------------------------------------------------------------|------------------|
| `objs`            | List or dictionary of pandas objects to be concatenated; required argument  | `pd.concat([df1, df2])` |
| `axis`            | Axis to concatenate along; default is rows (`axis=0` or `"index"`)          | `pd.concat([df1, df2], axis=1)` |
| `join`            | `"inner"` or `"outer"` (`"outer"` by default); controls intersection vs union of indexes | `pd.concat([df1, df2], join="inner")` |
| `keys`            | Values to associate with objects being concatenated, forming hierarchical index | `pd.concat([df1, df2], keys=["A","B"])` |
| `levels`          | Specific indexes to use as hierarchical index levels if `keys` passed       | `pd.concat([df1, df2], keys=["A","B"], levels=[["A","B"]])` |
| `names`           | Names for created hierarchical levels if `keys`/`levels` passed             | `pd.concat([df1, df2], keys=["A","B"], names=["source"])` |
| `ignore_index`    | Do not preserve indexes; produce new range index                            | `pd.concat([df1, df2], ignore_index=True)` |
| `verify_integrity`| Check new axis for duplicates and raise exception if found; default `False` | `pd.concat([df1, df2], verify_integrity=True)` |

Combining Data with Overlap

In [146]:
a=pd.Series([np.nan,2.5,0.0,3.5,4.5,np.nan],
            index=list("fedcba"))

In [148]:
b=pd.Series([0., np.nan, 2., np.nan, np.nan, 5.],
            index=list("abcdef"))

In [149]:
a

a    0.0
b    NaN
c    2.0
d    NaN
e    NaN
f    5.0
dtype: float64

In [150]:
b

a    0.0
b    NaN
c    2.0
d    NaN
e    NaN
f    5.0
dtype: float64

In [151]:
np.where(pd.isna(a),b,a)

array([ 0., nan,  2., nan, nan,  5.])

In [152]:
a.combine_first(b)

a    0.0
b    NaN
c    2.0
d    NaN
e    NaN
f    5.0
dtype: float64

In [154]:
df1=pd.DataFrame({
"a": [1., np.nan, 5., np.nan],                    
"b": [np.nan, 2., np.nan, 6.],
"c": range(2, 18, 4)  
})

In [155]:
df2 = pd.DataFrame({"a": [5., 4., np.nan, 3., 7.],
                    "b": [np.nan, 3., 4., 6., 8.]})

In [156]:
df1

     a    b   c
0  1.0  NaN   2
1  NaN  2.0   6
2  5.0  NaN  10
3  NaN  6.0  14

In [157]:
df2

     a    b
0  5.0  NaN
1  4.0  3.0
2  NaN  4.0
3  3.0  6.0
4  7.0  8.0

In [158]:
df1.combine_first(df2)

     a    b     c
0  1.0  NaN   2.0
1  4.0  2.0   6.0
2  5.0  4.0  10.0
3  3.0  6.0  14.0
4  7.0  8.0   NaN

# 8.3 Reshaping and Pivoting

Reshaping with Hierarchical Indexing