In [2]:
import numpy as np
import pandas as pd

In [3]:
df=pd.DataFrame({
    "key1":["a","a",None,"b","b","a",None],
    "key2":pd.Series([1,2,1,2,1,None,1],
    dtype="Int64"),
    "data1":np.random.standard_normal(7),
    "data2":np.random.standard_normal(7)
                 })

In [4]:
df

   key1  key2     data1     data2
0     a     1  0.065616 -0.996695
1     a     2 -1.766280 -0.865993
2  None     1 -0.587372  0.668722
3     b     2  0.956936 -0.139594
4     b     1 -0.383593 -1.062922
5     a  <NA> -1.491275  1.966636
6  None     1  0.385922 -0.689566

In [5]:
grouped=df["data1"].groupby(df["key1"])

In [6]:
grouped

In [7]:
grouped.mean()

key1
a   -1.063980
b    0.286672
Name: data1, dtype: float64

In [8]:
means=df["data1"].groupby([df["key1"],df["key2"]]).mean()

In [9]:
means

key1  key2
a     1       0.065616
      2      -1.766280
b     1      -0.383593
      2       0.956936
Name: data1, dtype: float64

In [10]:
means.unstack()

key2         1         2
key1
a     0.065616 -1.766280
b    -0.383593  0.956936

In [11]:
states=np.array(["OH", "CA", "CA", "OH", "OH", "CA", "OH"])

In [12]:
years= [2005, 2005, 2006, 2005, 2006, 2005, 2006]

In [13]:
df["data1"].groupby([states,years]).mean()

CA  2005   -1.628778
    2006   -0.587372
OH  2005    0.511276
    2006    0.001164
Name: data1, dtype: float64

In [14]:
df.groupby("key1").mean()

      key2     data1     data2
key1
a      1.5 -1.063980  0.034649
b      1.5  0.286672 -0.601258

In [15]:
df.groupby("key2").mean()

TypeError: agg function failed [how->mean,dtype->object]

In [ ]:
df.groupby(["key1", "key2"]).mean()

              data1     data2
key1 key2
a    1    -0.820693 -1.568591
     2    -0.837715  0.028946
b    1    -0.836127 -0.557881
     2     0.699768  0.083363

In [ ]:
df.groupby(["key1","key2"]).size()

key1  key2
a     1       1
      2       1
b     1       1
      2       1
dtype: int64

In [ ]:
df.groupby("key1",dropna=False).size()

key1
a      3
b      2
NaN    2
dtype: int64

In [ ]:
df.groupby(["key1","key2"],dropna=False).size()

key1  key2
a     1       1
      2       1
      <NA>    1
b     1       1
      2       1
NaN   1       2
dtype: int64

In [ ]:
df.groupby("key1").count()

      key2  data1  data2
key1
a        2      3      3
b        2      2      2

# Iterating over Groups

In [ ]:
for name,group in df.groupby("key1"):
    print(name)
    print(group)

a
  key1  key2     data1     data2
0    a     1 -0.820693 -1.568591
1    a     2 -0.837715  0.028946
5    a  <NA>  1.175737  2.006342
b
  key1  key2     data1     data2
3    b     2  0.699768  0.083363
4    b     1 -0.836127 -0.557881

In [ ]:
for (k1,k2),group in df.groupby(["key1","key2"]):
    print((k1,k2))
    print(group)

('a', np.int64(1))
  key1  key2     data1     data2
0    a     1 -0.820693 -1.568591
('a', np.int64(2))
  key1  key2     data1     data2
1    a     2 -0.837715  0.028946
('b', np.int64(1))
  key1  key2     data1     data2
4    b     1 -0.836127 -0.557881
('b', np.int64(2))
  key1  key2     data1     data2
3    b     2  0.699768  0.083363

In [ ]:
pieces={
    name:group for name,group in df.groupby("key1")
}

In [ ]:
pieces

{'a':   key1  key2     data1     data2
 0    a     1 -0.820693 -1.568591
 1    a     2 -0.837715  0.028946
 5    a  <NA>  1.175737  2.006342,
 'b':   key1  key2     data1     data2
 3    b     2  0.699768  0.083363
 4    b     1 -0.836127 -0.557881}

In [ ]:
grouped=df.groupby({
    "key1":"key","key2":"key","data1":"data","data2":"data"
},axis="columns")

C:\Users\Prathamesh Gawas\AppData\Local\Temp\ipykernel_27636\3898509450.py:1: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  grouped=df.groupby({

In [ ]:
for group_key ,group_values in grouped:
    print(group_key)
    print(group_values)

data
      data1     data2
0 -0.820693 -1.568591
1 -0.837715  0.028946
2 -1.118366  1.400539
3  0.699768  0.083363
4 -0.836127 -0.557881
5  1.175737  2.006342
6 -1.190913 -1.707355
key
   key1  key2
0     a     1
1     a     2
2  None     1
3     b     2
4     b     1
5     a  <NA>
6  None     1

Selecting a Column or Subset of Columns

In [ ]:
df.groupby("key1")["data1"]
df.groupby("key1")[["data1"]]

In [ ]:
df["data1"].groupby(df["key1"])
df["data2"].groupby(df["key1"])

In [ ]:
df

   key1  key2     data1     data2
0     a     1 -0.820693 -1.568591
1     a     2 -0.837715  0.028946
2  None     1 -1.118366  1.400539
3     b     2  0.699768  0.083363
4     b     1 -0.836127 -0.557881
5     a  <NA>  1.175737  2.006342
6  None     1 -1.190913 -1.707355

In [ ]:
df.groupby(["key1","key2"])[["data1"]].mean()

              data1
key1 key2
a    1    -0.820693
     2    -0.837715
b    1    -0.836127
     2     0.699768

In [ ]:
s_grouped=df.groupby(["key1","key2"])["data2"]

In [ ]:
s_grouped

In [ ]:
s_grouped.mean()

key1  key2
a     1      -1.568591
      2       0.028946
b     1      -0.557881
      2       0.083363
Name: data2, dtype: float64

Grouping with Dictionaries and Series

In [ ]:
people=pd.DataFrame(
    np.random.standard_normal((5,5)),
    columns=["a","b","c","d","e"],
    index=["Joe","Steve","Wanda","Jill","Trey"]
)

In [ ]:
people.iloc[2:3,[1,2]]=np.nan

In [ ]:
people

              a         b         c         d         e
Joe   -1.465460 -0.895543 -0.170783  1.040465 -0.267869
Steve  0.407657 -0.250176 -0.096558  1.766970 -2.028193
Wanda  0.591231       NaN       NaN  1.363411 -0.148327
Jill   1.661321  0.685653  0.161907  0.786857  0.492464
Trey   0.507842  0.170878 -0.080122  0.241011  0.288239

In [ ]:
mapping={
    "a": "red", "b": "red", "c": "blue",
    "d": "blue", "e": "red", "f" : "orange"}

In [ ]:
by_column=people.groupby(mapping,axis="columns")

C:\Users\Prathamesh Gawas\AppData\Local\Temp\ipykernel_27636\2149570058.py:1: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  by_column=people.groupby(mapping,axis="columns")

In [ ]:
by_column.sum()

           blue       red
Joe    0.869683 -2.628872
Steve  1.670411 -1.870712
Wanda  1.363411  0.442904
Jill   0.948764  2.839438
Trey   0.160889  0.966959

In [ ]:
map_series=pd.Series(mapping)

In [ ]:
map_series

a       red
b       red
c      blue
d      blue
e       red
f    orange
dtype: object

In [ ]:
people.groupby(map_series,axis="columns").count()

C:\Users\Prathamesh Gawas\AppData\Local\Temp\ipykernel_27636\172532021.py:1: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  people.groupby(map_series,axis="columns").count()

       blue  red
Joe       2    3
Steve     2    3
Wanda     1    2
Jill      2    3
Trey      2    3

Grouping with Functions

In [ ]:
people.groupby(len).sum()

          a         b         c         d         e
3 -1.465460 -0.895543 -0.170783  1.040465 -0.267869
4  2.169163  0.856531  0.081785  1.027868  0.780703
5  0.998888 -0.250176 -0.096558  3.130381 -2.176520

In [ ]:
key_list=["one","one","one","two","two"]

In [ ]:
people.groupby([len,key_list]).min()

              a         b         c         d         e
3 one -1.465460 -0.895543 -0.170783  1.040465 -0.267869
4 two  0.507842  0.170878 -0.080122  0.241011  0.288239
5 one  0.407657 -0.250176 -0.096558  1.363411 -2.028193

Grouping by Index Levels

In [ ]:
columns=pd.MultiIndex.from_arrays([
    ["US","US","US","JP","JP"],
    [1,3,5,1,3]],
                                  names=["cty","tenor"])

In [ ]:
hier_df=pd.DataFrame(np.random.standard_normal((4,5)),columns=columns)

In [ ]:
hier_df

cty          US                            JP
tenor         1         3         5         1         3
0      0.476899 -0.761348 -0.577145 -1.577307  0.725196
1      0.895017  0.709642  0.685874  0.681582  0.909708
2      0.225746 -2.481837 -0.968169 -0.824168 -1.576020
3      1.018485  1.609951  0.130310  0.358471 -0.827691

In [ ]:
hier_df.groupby(level="cty",axis="columns").count()

C:\Users\Prathamesh Gawas\AppData\Local\Temp\ipykernel_27636\1991154737.py:1: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  hier_df.groupby(level="cty",axis="columns").count()

cty  JP  US
0     2   3
1     2   3
2     2   3
3     2   3

# 10.2 Data Aggregation

Function name Description
any, all
Return True if any (one or more values) or all non-NA values are “truthy”
count
Number of non-NA values
cummin, cummax Cumulative minimum and maximum of non-NA values
cumsum
Cumulative sum of non-NA values
cumprod
Cumulative product of non-NA values
first, last
First and last non-NA values
mean
Mean of non-NA values
median
Arithmetic median of non-NA values
min, max
Minimum and maximum of non-NA values
nth
Retrieve value that would appear at position n with the data in sorted order
ohlc
Compute four “open-high-low-close” statistics for time series-like data
prod
Product of non-NA values
quantile
Compute sample quantile
rank
Ordinal ranks of non-NA values, like calling Series.rank
size
Compute group sizes, returning result as a Series
sum
Sum of non-NA values
std, var
Sample standard deviation and varianc

In [ ]:
df

   key1  key2     data1     data2
0     a     1 -0.820693 -1.568591
1     a     2 -0.837715  0.028946
2  None     1 -1.118366  1.400539
3     b     2  0.699768  0.083363
4     b     1 -0.836127 -0.557881
5     a  <NA>  1.175737  2.006342
6  None     1 -1.190913 -1.707355

In [ ]:
grouped=df.groupby("key1")

In [ ]:
grouped["data1"].nsmallest(2)

key1
a     1   -0.837715
      0   -0.820693
b     4   -0.836127
      3    0.699768
Name: data1, dtype: float64

In [ ]:
def peak_to_peak(arr):
    return arr.max()-arr.min()

In [ ]:
grouped.agg(peak_to_peak)

      key2     data1     data2
key1
a        1  2.013451  3.574933
b        1  1.535895  0.641244

In [ ]:
grouped.describe()

      key2                                           data1           ...  \
     count mean       std  min   25%  50%   75%  max count     mean  ...
key1                                                                 ...
a      2.0  1.5  0.707107  1.0  1.25  1.5  1.75  2.0   3.0 -0.16089  ...
b      2.0  1.5  0.707107  1.0  1.25  1.5  1.75  2.0   2.0 -0.06818  ...

                         data2                                          \
           75%       max count      mean       std       min       25%
key1
a     0.177522  1.175737   3.0  0.155565  1.790827 -1.568591 -0.769823
b     0.315794  0.699768   2.0 -0.237259  0.453428 -0.557881 -0.397570


           50%       75%       max
key1
a     0.028946  1.017644  2.006342
b    -0.237259 -0.076948  0.083363

[2 rows x 24 columns]

Column-Wise and Multiple Function Application

In [ ]:
tips=pd.read_csv("examples/tips.csv")

In [ ]:
tips.head()

   total_bill   tip smoker  day    time  size
0       16.99  1.01     No  Sun  Dinner     2
1       10.34  1.66     No  Sun  Dinner     3
2       21.01  3.50     No  Sun  Dinner     3
3       23.68  3.31     No  Sun  Dinner     2
4       24.59  3.61     No  Sun  Dinner     4

In [ ]:
tips["tip_pct"]=tips["tip"]/tips["total_bill"]

In [ ]:
tips.head()

   total_bill   tip smoker  day    time  size   tip_pct
0       16.99  1.01     No  Sun  Dinner     2  0.059447
1       10.34  1.66     No  Sun  Dinner     3  0.160542
2       21.01  3.50     No  Sun  Dinner     3  0.166587
3       23.68  3.31     No  Sun  Dinner     2  0.139780
4       24.59  3.61     No  Sun  Dinner     4  0.146808

In [ ]:
grouped=tips.groupby(["day","smoker"])

In [ ]:
grouped_pct=grouped["tip_pct"]

In [ ]:
grouped_pct.agg("mean")

day   smoker
Fri   No        0.151650
      Yes       0.174783
Sat   No        0.158048
      Yes       0.147906
Sun   No        0.160113
      Yes       0.187250
Thur  No        0.160298
      Yes       0.163863
Name: tip_pct, dtype: float64

In [ ]:
grouped_pct.agg(["mean","std",peak_to_peak])

                 mean       std  peak_to_peak
day  smoker
Fri  No      0.151650  0.028123      0.067349
     Yes     0.174783  0.051293      0.159925
Sat  No      0.158048  0.039767      0.235193
     Yes     0.147906  0.061375      0.290095
Sun  No      0.160113  0.042347      0.193226
     Yes     0.187250  0.154134      0.644685
Thur No      0.160298  0.038774      0.193350
     Yes     0.163863  0.039389      0.151240

In [ ]:
grouped_pct.agg([("average","mean"),("stdev",np.std)])

C:\Users\Prathamesh Gawas\AppData\Local\Temp\ipykernel_27636\3139945052.py:1: FutureWarning: The provided callable <function std at 0x0000025538735120> is currently using SeriesGroupBy.std. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "std" instead.
  grouped_pct.agg([("average","mean"),("stdev",np.std)])

              average     stdev
day  smoker
Fri  No      0.151650  0.028123
     Yes     0.174783  0.051293
Sat  No      0.158048  0.039767
     Yes     0.147906  0.061375
Sun  No      0.160113  0.042347
     Yes     0.187250  0.154134
Thur No      0.160298  0.038774
     Yes     0.163863  0.039389

In [ ]:
functions=["count","mean","max"]

In [ ]:
result=grouped[["tip_pct","total_bill"]].agg(functions)

In [ ]:
result

            tip_pct                     total_bill
              count      mean       max      count       mean    max
day  smoker
Fri  No           4  0.151650  0.187735          4  18.420000  22.75
     Yes         15  0.174783  0.263480         15  16.813333  40.17
Sat  No          45  0.158048  0.291990         45  19.661778  48.33
     Yes         42  0.147906  0.325733         42  21.276667  50.81
Sun  No          57  0.160113  0.252672         57  20.506667  48.17
     Yes         19  0.187250  0.710345         19  24.120000  45.35
Thur No          45  0.160298  0.266312         45  17.113111  41.19
     Yes         17  0.163863  0.241255         17  19.190588  43.11

In [ ]:
result["tip_pct"]

             count      mean       max
day  smoker
Fri  No          4  0.151650  0.187735
     Yes        15  0.174783  0.263480
Sat  No         45  0.158048  0.291990
     Yes        42  0.147906  0.325733
Sun  No         57  0.160113  0.252672
     Yes        19  0.187250  0.710345
Thur No         45  0.160298  0.266312
     Yes        17  0.163863  0.241255

In [ ]:
ftuples=[("Average","mean"),("Variance",np.var)]

In [ ]:
grouped[["tip_pct","total_bill"]].agg(ftuples)

C:\Users\Prathamesh Gawas\AppData\Local\Temp\ipykernel_27636\2321675487.py:1: FutureWarning: The provided callable <function var at 0x0000025538735260> is currently using SeriesGroupBy.var. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "var" instead.
  grouped[["tip_pct","total_bill"]].agg(ftuples)

              tip_pct           total_bill
              Average  Variance    Average    Variance
day  smoker
Fri  No      0.151650  0.000791  18.420000   25.596333
     Yes     0.174783  0.002631  16.813333   82.562438
Sat  No      0.158048  0.001581  19.661778   79.908965
     Yes     0.147906  0.003767  21.276667  101.387535
Sun  No      0.160113  0.001793  20.506667   66.099980
     Yes     0.187250  0.023757  24.120000  109.046044
Thur No      0.160298  0.001503  17.113111   59.625081
     Yes     0.163863  0.001551  19.190588   69.808518

In [ ]:
grouped.agg({"tip":np.max,"size":"sum"})

C:\Users\Prathamesh Gawas\AppData\Local\Temp\ipykernel_27636\435802830.py:1: FutureWarning: The provided callable <function max at 0x00000255387345E0> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  grouped.agg({"tip":np.max,"size":"sum"})

               tip  size
day  smoker
Fri  No       3.50     9
     Yes      4.73    31
Sat  No       9.00   115
     Yes     10.00   104
Sun  No       6.00   167
     Yes      6.50    49
Thur No       6.70   112
     Yes      5.00    40

In [ ]:
grouped.agg({
    "tip_pct":["min","max","mean","std"], "size":"sum"
})

              tip_pct                               size
                  min       max      mean       std  sum
day  smoker
Fri  No      0.120385  0.187735  0.151650  0.028123    9
     Yes     0.103555  0.263480  0.174783  0.051293   31
Sat  No      0.056797  0.291990  0.158048  0.039767  115
     Yes     0.035638  0.325733  0.147906  0.061375  104
Sun  No      0.059447  0.252672  0.160113  0.042347  167
     Yes     0.065660  0.710345  0.187250  0.154134   49
Thur No      0.072961  0.266312  0.160298  0.038774  112
     Yes     0.090014  0.241255  0.163863  0.039389   40

Returning Aggregated Data Without Row Indexes

In [ ]:
tips.groupby(["day","smoker"], as_index=False).mean()

TypeError: agg function failed [how->mean,dtype->object]

# 10.3 Apply: General split-apply-combine

In [ ]:
tips

     total_bill   tip smoker   day    time  size   tip_pct
0         16.99  1.01     No   Sun  Dinner     2  0.059447
1         10.34  1.66     No   Sun  Dinner     3  0.160542
2         21.01  3.50     No   Sun  Dinner     3  0.166587
3         23.68  3.31     No   Sun  Dinner     2  0.139780
4         24.59  3.61     No   Sun  Dinner     4  0.146808
..          ...   ...    ...   ...     ...   ...       ...
239       29.03  5.92     No   Sat  Dinner     3  0.203927
240       27.18  2.00    Yes   Sat  Dinner     2  0.073584
241       22.67  2.00    Yes   Sat  Dinner     2  0.088222
242       17.82  1.75     No   Sat  Dinner     2  0.098204
243       18.78  3.00     No  Thur  Dinner     2  0.159744

[244 rows x 7 columns]

In [ ]:
def top(df,n=5,column="tip_pct"):
    return df.sort_values(column,ascending=False)[:n]

In [ ]:
top(tips,n=6)

     total_bill   tip smoker  day    time  size   tip_pct
172        7.25  5.15    Yes  Sun  Dinner     2  0.710345
178        9.60  4.00    Yes  Sun  Dinner     2  0.416667
67         3.07  1.00    Yes  Sat  Dinner     1  0.325733
232       11.61  3.39     No  Sat  Dinner     2  0.291990
183       23.17  6.50    Yes  Sun  Dinner     4  0.280535
109       14.31  4.00    Yes  Sat  Dinner     2  0.279525

In [ ]:
tips.groupby("smoker").apply(top)

C:\Users\Prathamesh Gawas\AppData\Local\Temp\ipykernel_27636\2530541573.py:1: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  tips.groupby("smoker").apply(top)

            total_bill   tip smoker   day    time  size   tip_pct
smoker
No     232       11.61  3.39     No   Sat  Dinner     2  0.291990
       149        7.51  2.00     No  Thur   Lunch     2  0.266312
       51        10.29  2.60     No   Sun  Dinner     2  0.252672
       185       20.69  5.00     No   Sun  Dinner     5  0.241663
       88        24.71  5.85     No  Thur   Lunch     2  0.236746
Yes    172        7.25  5.15    Yes   Sun  Dinner     2  0.710345
       178        9.60  4.00    Yes   Sun  Dinner     2  0.416667
       67         3.07  1.00    Yes   Sat  Dinner     1  0.325733
       183       23.17  6.50    Yes   Sun  Dinner     4  0.280535
       109       14.31  4.00    Yes   Sat  Dinner     2  0.279525

In [ ]:
tips.groupby(["smoker","day"]).apply(top,n=1,column="total_bill")

C:\Users\Prathamesh Gawas\AppData\Local\Temp\ipykernel_27636\470388052.py:1: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  tips.groupby(["smoker","day"]).apply(top,n=1,column="total_bill")

                 total_bill    tip smoker   day    time  size   tip_pct
smoker day
No     Fri  94        22.75   3.25     No   Fri  Dinner     2  0.142857
       Sat  212       48.33   9.00     No   Sat  Dinner     4  0.186220
       Sun  156       48.17   5.00     No   Sun  Dinner     6  0.103799
       Thur 142       41.19   5.00     No  Thur   Lunch     5  0.121389
Yes    Fri  95        40.17   4.73    Yes   Fri  Dinner     4  0.117750
       Sat  170       50.81  10.00    Yes   Sat  Dinner     3  0.196812
       Sun  182       45.35   3.50    Yes   Sun  Dinner     3  0.077178
       Thur 197       43.11   5.00    Yes  Thur   Lunch     4  0.115982

In [ ]:
result=tips.groupby("smoker")["tip_pct"].describe()

In [ ]:
result

,count,mean,std,min,25%,50%,75%,max
smoker,,,,,,,,
No,151.0,0.159328,0.039910,0.056797,0.136906,0.155625,0.185014,0.291990
Yes,93.0,0.163196,0.085119,0.035638,0.106771,0.153846,0.195059,0.710345

In [ ]:
result.unstack("smoker")

       smoker
count  No        151.000000
       Yes        93.000000
mean   No          0.159328
       Yes         0.163196
std    No          0.039910
       Yes         0.085119
min    No          0.056797
       Yes         0.035638
25%    No          0.136906
       Yes         0.106771
50%    No          0.155625
       Yes         0.153846
75%    No          0.185014
       Yes         0.195059
max    No          0.291990
       Yes         0.710345
dtype: float64

In [ ]:
def f(group):
    return group.describe()

In [ ]:
grouped.apply(f)

C:\Users\Prathamesh Gawas\AppData\Local\Temp\ipykernel_27636\833689054.py:1: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  grouped.apply(f)

                   total_bill       tip  size   tip_pct
day  smoker
Fri  No     count    4.000000  4.000000  4.00  4.000000
            mean    18.420000  2.812500  2.25  0.151650
            std      5.059282  0.898494  0.50  0.028123
            min     12.460000  1.500000  2.00  0.120385
            25%     15.100000  2.625000  2.00  0.137239
...                       ...       ...   ...       ...
Thur Yes    min     10.340000  2.000000  2.00  0.090014
            25%     13.510000  2.000000  2.00  0.148038
            50%     16.470000  2.560000  2.00  0.153846
            75%     19.810000  4.000000  2.00  0.194837
            max     43.110000  5.000000  4.00  0.241255

[64 rows x 4 columns]

Suppressing the Group Keys

In [ ]:
tips.groupby("smoker",group_keys=False).apply(top)

C:\Users\Prathamesh Gawas\AppData\Local\Temp\ipykernel_27636\507294496.py:1: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  tips.groupby("smoker",group_keys=False).apply(top)

     total_bill   tip smoker   day    time  size   tip_pct
232       11.61  3.39     No   Sat  Dinner     2  0.291990
149        7.51  2.00     No  Thur   Lunch     2  0.266312
51        10.29  2.60     No   Sun  Dinner     2  0.252672
185       20.69  5.00     No   Sun  Dinner     5  0.241663
88        24.71  5.85     No  Thur   Lunch     2  0.236746
172        7.25  5.15    Yes   Sun  Dinner     2  0.710345
178        9.60  4.00    Yes   Sun  Dinner     2  0.416667
67         3.07  1.00    Yes   Sat  Dinner     1  0.325733
183       23.17  6.50    Yes   Sun  Dinner     4  0.280535
109       14.31  4.00    Yes   Sat  Dinner     2  0.279525

Quantile and Bucket Analysis

In [ ]:
frame=pd.DataFrame({
    "data1":np.random.standard_normal(1000),
    "data2":np.random.standard_normal(1000)
})

In [ ]:
frame.head()

      data1     data2
0 -1.645380  0.585037
1 -0.440185 -1.436131
2  0.315749 -1.993022
3 -0.404646 -0.568003
4  0.782852 -0.154807

In [ ]:
quartiles=pd.cut(frame["data1"],4)

In [ ]:
quartiles.head(10)

0    (-3.055, -1.579]
1     (-1.579, -0.11]
2      (-0.11, 1.359]
3     (-1.579, -0.11]
4      (-0.11, 1.359]
5      (-0.11, 1.359]
6      (-0.11, 1.359]
7      (-0.11, 1.359]
8    (-3.055, -1.579]
9     (-1.579, -0.11]
Name: data1, dtype: category
Categories (4, interval[float64, right]): [(-3.055, -1.579] < (-1.579, -0.11] < (-0.11, 1.359] < (1.359, 2.828]]

In [ ]:
def get_stats(group):
    return pd.DataFrame(
        {
            "min":group.min(),
            "max":group.max(),
            "count":group.count(),
            "mean":group.mean()
        }
    )

In [ ]:
grouped=frame.groupby(quartiles)

C:\Users\Prathamesh Gawas\AppData\Local\Temp\ipykernel_27636\38721795.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  grouped=frame.groupby(quartiles)

In [ ]:
grouped.apply(get_stats)

                             min       max  count      mean
data1
(-3.055, -1.579] data1 -3.048663 -1.582419     69 -2.008801
                 data2 -2.379040  3.175464     69 -0.038168
(-1.579, -0.11]  data1 -1.579070 -0.111380    366 -0.714533
                 data2 -2.880074  3.377080    366  0.109342
(-0.11, 1.359]   data1 -0.109332  1.354747    473  0.515791
                 data2 -2.452682  3.792682    473 -0.011809
(1.359, 2.828]   data1  1.381969  2.828094     92  1.872104
                 data2 -1.707720  2.096055     92 -0.000843

In [ ]:
grouped.agg(["min","max","count","mean"])

                     data1                               data2            \
                       min       max count      mean       min       max
data1
(-3.055, -1.579] -3.048663 -1.582419    69 -2.008801 -2.379040  3.175464
(-1.579, -0.11]  -1.579070 -0.111380   366 -0.714533 -2.880074  3.377080
(-0.11, 1.359]   -0.109332  1.354747   473  0.515791 -2.452682  3.792682
(1.359, 2.828]    1.381969  2.828094    92  1.872104 -1.707720  2.096055


                 count      mean
data1
(-3.055, -1.579]    69 -0.038168
(-1.579, -0.11]    366  0.109342
(-0.11, 1.359]     473 -0.011809
(1.359, 2.828]      92 -0.000843

In [ ]:
quartiles_samp=pd.qcut(frame["data1"],4,labels=False)

In [ ]:
quartiles_samp.head()

0    0
1    1
2    2
3    1
4    3
Name: data1, dtype: int64

In [ ]:
grouped=frame.groupby(quartiles_samp)

In [ ]:
grouped.apply(get_stats)

                  min       max  count      mean
data1
0     data1 -3.048663 -0.699192    250 -1.312298
      data2 -2.880074  3.377080    250  0.077246
1     data1 -0.695287  0.049778    250 -0.294085
      data2 -2.452682  2.726692    250  0.050689
2     data1  0.049837  0.695532    250  0.359872
      data2 -2.382470  3.048558    250  0.058760
3     data1  0.696521  2.828094    250  1.310816
      data2 -2.416160  3.792682    250 -0.059806

Example: Filling Missing Values with Group-Specific
Values

In [ ]:
s=pd.Series(np.random.standard_normal(6))

In [ ]:
s

0   -1.195609
1    0.246552
2   -0.179820
3    0.176098
4   -0.663582
5    0.009023
dtype: float64

In [ ]:
s[::2]=np.nan

In [ ]:
s

0         NaN
1    0.246552
2         NaN
3    0.176098
4         NaN
5    0.009023
dtype: float64

In [ ]:
s.fillna(s.mean())

0    0.143891
1    0.246552
2    0.143891
3    0.176098
4    0.143891
5    0.009023
dtype: float64

In [ ]:
states = ["Ohio", "New York", "Vermont", "Florida",        
"Oregon", "Nevada", "California", "Idaho"]

In [ ]:
group_key = ["East", "East", "East", "East",           
"West", "West", "West", "West"]

In [ ]:
data=pd.Series(np.random.standard_normal(8),index=states)

In [ ]:
data

Ohio         -0.673041
New York     -1.530374
Vermont       0.559728
Florida       0.979028
Oregon        0.044278
Nevada       -2.059728
California   -0.793101
Idaho        -0.085275
dtype: float64

In [ ]:
data[["Vermont","Nevada","Idaho"]]=np.nan

In [ ]:
data

Ohio         -0.673041
New York     -1.530374
Vermont            NaN
Florida       0.979028
Oregon        0.044278
Nevada             NaN
California   -0.793101
Idaho              NaN
dtype: float64

In [ ]:
data.groupby(group_key).size()

East    4
West    4
dtype: int64

In [ ]:
data.groupby(group_key).count()

East    3
West    2
dtype: int64

In [ ]:
data.groupby(group_key).mean()

East   -0.408129
West   -0.374412
dtype: float64

In [ ]:
def fill_mean(group):
    return group.fillna(group.mean())

In [ ]:
data.groupby(group_key).apply(fill_mean)

East  Ohio         -0.673041
      New York     -1.530374
      Vermont      -0.408129
      Florida       0.979028
West  Oregon        0.044278
      Nevada       -0.374412
      California   -0.793101
      Idaho        -0.374412
dtype: float64

In [ ]:
fill_values={
    "East":0.5,"West":-1
}

In [ ]:
def fill_func(group):
    return group.fillna(fill_values[group.name])

In [ ]:
data.groupby(group_key).apply(fill_func)

East  Ohio         -0.673041
      New York     -1.530374
      Vermont       0.500000
      Florida       0.979028
West  Oregon        0.044278
      Nevada       -1.000000
      California   -0.793101
      Idaho        -1.000000
dtype: float64

Example: Random Sampling and Permutation

In [ ]:
suits = ["H", "S", "C", "D"]  # Hearts, Spades, Clubs, Diamonds
card_val = (list(range(1, 11)) + [10] * 3) * 4
base_names = ["A"] + list(range(2, 11)) + ["J", "K", "Q"]
cards = []

for suit in suits:
    cards.extend(str(num) + suit for num in base_names)
deck = pd.Series(card_val, index=cards)

In [ ]:
deck.head()

AH    1
2H    2
3H    3
4H    4
5H    5
dtype: int64

In [ ]:
def draw(deck,n=5):
    return deck.sample(n)

In [ ]:
draw(deck)

7C    7
2S    2
3S    3
7D    7
2D    2
dtype: int64

In [ ]:
def get_suit(card):
    return card[-1]

In [ ]:
deck.groupby(get_suit).apply(draw,n=2)

C  2C      2
   6C      6
D  7D      7
   6D      6
H  QH     10
   10H    10
S  6S      6
   8S      8
dtype: int64

In [ ]:
deck.groupby(get_suit,group_keys=False).apply(draw,n=2)

9C     9
7C     7
3D     3
2D     2
8H     8
7H     7
JS    10
AS     1
dtype: int64

Example: Group Weighted Average and Correlation

In [16]:
df=pd.DataFrame({
    "category":["a","a","a","a","b","b","b","b"],
    "data":np.random.standard_normal(8),
    "weights":np.random.uniform(size=8)
})

In [17]:
df

  category      data   weights
0        a -0.403979  0.159151
1        a -0.716515  0.731896
2        a  1.390571  0.768622
3        a -0.014373  0.033395
4        b -0.145878  0.740574
5        b  0.097040  0.076536
6        b  0.154176  0.178267
7        b -0.682610  0.542065

In [18]:
grouped=df.groupby("category")

In [19]:
def get_wavg(group):
    return np.average(group["data"],weights=group["weights"])

In [20]:
grouped.apply(get_wavg)

C:\Users\Prathamesh Gawas\AppData\Local\Temp\ipykernel_33628\4286695940.py:1: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  grouped.apply(get_wavg)

category
a    0.283294
b   -0.288233
dtype: float64