7.1 Handling Missing Data

In [2]:
import pandas as pd
import numpy as np

In [3]:
float_data=pd.Series([1.2,-3.5,np.nan,0])

In [4]:
float_data

0    1.2
1   -3.5
2    NaN
3    0.0
dtype: float64

In [5]:
float_data.isna()

0    False
1    False
2     True
3    False
dtype: bool

In [6]:
string_data=pd.Series([
    "aardvark",np.nan,None,"avocado"
])

In [7]:
string_data

0    aardvark
1         NaN
2        None
3     avocado
dtype: object

In [8]:
string_data.isna()

0    False
1     True
2     True
3    False
dtype: bool

In [9]:
float_data=pd.Series([1,2,None],dtype="float64")

In [10]:
float_data

0    1.0
1    2.0
2    NaN
dtype: float64

In [11]:
float_data.isna()

0    False
1    False
2     True
dtype: bool

## Table 7-1. NA handling object methods

| Method   | Description                                                                 | Example (Python) | Output |
|----------|-----------------------------------------------------------------------------|------------------|--------|
| `dropna` | Filter axis labels based on whether values for each label have missing data, with varying thresholds for how much missing data to tolerate | `pd.Series([1, np.nan, 3]).dropna()` | `[1.0, 3.0]` |
| `fillna` | Fill in missing data with some value or using an interpolation method such as `"ffill"` or `"bfill"` | `pd.Series([1, np.nan, 3]).fillna(0)` | `[1.0, 0.0, 3.0]` |
| `isna`   | Return Boolean values indicating which values are missing/NA                | `pd.Series([1, np.nan, 3]).isna()` | `[False, True, False]` |
| `notna`  | Negation of `isna`, returns True for non-NA values and False for NA values  | `pd.Series([1, np.nan, 3]).notna()` | `[True, False, True]` |

Filtering Out Missing Data

In [12]:
data=pd.Series(
    [
        1,np.nan,3.5,np.nan,7
    ]
)

In [13]:
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [14]:
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [15]:
data = pd.DataFrame([[1., 6.5, 3.], [1., np.nan, np.nan],                   
[np.nan, np.nan, np.nan], [np.nan, 6.5, 3.]])

In [16]:
data

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [17]:
data.dropna()

     0    1    2
0  1.0  6.5  3.0

Passing how="all" will drop only rows that are all NA:

In [18]:
data.dropna(how="all")

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [19]:
data[4]=np.nan

In [20]:
data

     0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

To drop columns in the same way, pass axis="columns":

In [21]:
data.dropna(axis="columns",how="all") # use rows instead of columns

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [22]:
df=pd.DataFrame(np.random.standard_normal((7,3)))

In [23]:
df

          0         1         2
0  0.996478 -0.959624 -1.068726
1 -0.814733 -0.554775  0.039947
2 -2.084374  1.521694  0.523946
3  1.106162  0.109783  0.541987
4  0.320041  1.139200 -1.117611
5  0.061144 -0.770173  1.885208
6  0.555834  2.092066 -0.712912

In [24]:
df.iloc[:4:1]=np.nan

In [25]:
df.iloc[:2,2]=np.nan

In [26]:
df

          0         1         2
0       NaN       NaN       NaN
1       NaN       NaN       NaN
2       NaN       NaN       NaN
3       NaN       NaN       NaN
4  0.320041  1.139200 -1.117611
5  0.061144 -0.770173  1.885208
6  0.555834  2.092066 -0.712912

In [27]:
df.dropna()

          0         1         2
4  0.320041  1.139200 -1.117611
5  0.061144 -0.770173  1.885208
6  0.555834  2.092066 -0.712912

thresh=2 → Sets a threshold: a row must have at least 2 non-NaN values to be kept.

If a row has fewer than 2 non-null entries, it will be dropped.

In [28]:
df.dropna(thresh=2)

          0         1         2
4  0.320041  1.139200 -1.117611
5  0.061144 -0.770173  1.885208
6  0.555834  2.092066 -0.712912

# Filling In Missing Data

In [29]:
df.fillna(0)

          0         1         2
0  0.000000  0.000000  0.000000
1  0.000000  0.000000  0.000000
2  0.000000  0.000000  0.000000
3  0.000000  0.000000  0.000000
4  0.320041  1.139200 -1.117611
5  0.061144 -0.770173  1.885208
6  0.555834  2.092066 -0.712912

In [30]:
df.fillna(
    {1:0.5,2:0}
)

          0         1         2
0       NaN  0.500000  0.000000
1       NaN  0.500000  0.000000
2       NaN  0.500000  0.000000
3       NaN  0.500000  0.000000
4  0.320041  1.139200 -1.117611
5  0.061144 -0.770173  1.885208
6  0.555834  2.092066 -0.712912

In [31]:
df=pd.DataFrame(np.random.standard_normal((6,3)))

In [32]:
df

          0         1         2
0 -1.394858  0.882315  0.901701
1  1.191385 -1.431312 -0.664312
2 -0.178895  0.116614 -0.985110
3  0.318478 -0.648349  2.571570
4 -0.224119  0.997798 -0.563764
5  0.316795 -0.536004  1.290986

In [33]:
df.iloc[2:,1]=np.nan

In [34]:
df.iloc[4:,2]=np.nan

In [35]:
df

          0         1         2
0 -1.394858  0.882315  0.901701
1  1.191385 -1.431312 -0.664312
2 -0.178895       NaN -0.985110
3  0.318478       NaN  2.571570
4 -0.224119       NaN       NaN
5  0.316795       NaN       NaN

In [36]:
df.fillna(method="ffill")

C:\Users\Prathamesh Gawas\AppData\Local\Temp\ipykernel_24312\3944122520.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="ffill")

          0         1         2
0 -1.394858  0.882315  0.901701
1  1.191385 -1.431312 -0.664312
2 -0.178895 -1.431312 -0.985110
3  0.318478 -1.431312  2.571570
4 -0.224119 -1.431312  2.571570
5  0.316795 -1.431312  2.571570

In [37]:
df.fillna(method="ffill",limit=2)

C:\Users\Prathamesh Gawas\AppData\Local\Temp\ipykernel_24312\3768739427.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="ffill",limit=2)

          0         1         2
0 -1.394858  0.882315  0.901701
1  1.191385 -1.431312 -0.664312
2 -0.178895 -1.431312 -0.985110
3  0.318478 -1.431312  2.571570
4 -0.224119       NaN  2.571570
5  0.316795       NaN  2.571570

In [38]:
data=pd.Series(
    [1.,np.nan,3.5,np.nan,7]
)

In [39]:
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [40]:
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

## Table 7-2. `fillna` function arguments

| Argument | Description                                                                 | Example (Python) | Output |
|----------|-----------------------------------------------------------------------------|------------------|--------|
| `value`  | Scalar value or dictionary-like object to use to fill missing values        | `pd.Series([1, np.nan, 3]).fillna(value=0)` | `[1.0, 0.0, 3.0]` |
| `method` | Interpolation method: `"bfill"` (backward fill) or `"ffill"` (forward fill); default is `None` | `pd.Series([1, np.nan, np.nan, 4]).fillna(method="ffill")` | `[1.0, 1.0, 1.0, 4.0]` |
| `axis`   | Axis to fill on (`"index"` or `"columns"`); default is `"index"`            | `df.fillna(method="ffill", axis="columns")` | Missing values filled column-wise |
| `limit`  | For forward/backward filling, maximum number of consecutive periods to fill | `pd.Series([1, np.nan, np.nan, 4]).fillna(method="ffill", limit=1)` | `[1.0, 1.0, NaN, 4.0]` |

# 7.2 Data Transformation

Removing Duplicates

In [41]:
data=pd.DataFrame({
    "k1":["one","two"]*3+["two"],
    "k2":[1,1,2,3,3,4,4]
})

In [42]:
data

    k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [43]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [44]:
data.drop_duplicates()

    k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [45]:
data["v1"]=range(7)

In [46]:
data

    k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [47]:
data.drop_duplicates(subset=["k1"])

    k1  k2  v1
0  one   1   0
1  two   1   1

In [48]:
data

    k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [49]:
data.drop_duplicates(["k1", "k2"],keep="last")

    k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

Transforming Data Using a Function or Mapping

In [50]:
data = pd.DataFrame({"food": ["bacon", "pulled pork", "bacon",
                             "pastrami", "corned beef", "bacon",
                             "pastrami", "honey ham", "nova lox"],
                      "ounces": [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})

In [51]:
data

          food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     pastrami     6.0
4  corned beef     7.5
5        bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [52]:
meat_to_animal = {
  "bacon": "pig",
  "pulled pork": "pig",
  "pastrami": "cow",
  "corned beef": "cow",
  "honey ham": "pig",
  "nova lox": "salmon"
}

In [53]:
data["animal"]=data["food"].map(meat_to_animal)

In [54]:
data

          food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     pastrami     6.0     cow
4  corned beef     7.5     cow
5        bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [55]:
def get_animal(x):
    return meat_to_animal[x]

In [56]:
data["food"].map(get_animal)

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

Replacing Values

In [57]:
data=pd.Series([1.,-999.,2.,-999.,-1000.,3.])

In [58]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [59]:
data.replace(-999,np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [60]:
data.replace([-999,-1000],np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [61]:
data.replace({-999:np.nan,-1000:0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

Renaming Axis Indexes

In [62]:
data=pd.DataFrame(
    np.arange(12).reshape((3,4)),
    index=["Ohio","Colorado","New York"],
    columns=["one","two","three","four"]
)

In [63]:
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [64]:
def transform(x):
    return x[:4].upper()

In [65]:
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [66]:
data.index=data.index.map(transform)

In [67]:
data

      one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [68]:
data.rename(index=str.title,columns=str.upper)

      ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [69]:
data.rename(
    index={"OHIO":"INDIANA"},
    columns={"three":"peekaboo"}
)

         one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

# Discretization and Binning

In [70]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [71]:
bins=[18, 25, 35, 60, 100]

In [72]:
age_catgeories=pd.cut(ages,bins)

In [73]:
age_catgeories

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [74]:
age_catgeories.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [75]:
age_catgeories.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]], dtype='interval[int64, right]')

In [76]:
age_catgeories.categories[0]

Interval(18, 25, closed='right')

In [77]:
pd.value_counts(age_catgeories)

C:\Users\Prathamesh Gawas\AppData\Local\Temp\ipykernel_24312\3827431093.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(age_catgeories)

(18, 25]     5
(25, 35]     3
(35, 60]     3
(60, 100]    1
Name: count, dtype: int64

In [78]:
pd.cut(ages,bins,right=False)

[[18, 25), [18, 25), [25, 35), [25, 35), [18, 25), ..., [25, 35), [60, 100), [35, 60), [35, 60), [25, 35)]
Length: 12
Categories (4, interval[int64, left]): [[18, 25) < [25, 35) < [35, 60) < [60, 100)]

In [79]:
group_names=["Youth","YoungAdult","MiddleAged","Senior"]

In [80]:
pd.cut(ages,bins,labels=group_names)
data1=pd.cut(ages,bins,labels=group_names)

In [81]:
data1.value_counts()

Youth         5
YoungAdult    3
MiddleAged    3
Senior        1
Name: count, dtype: int64

In [82]:
data=np.random.uniform(size=20)

In [83]:
data

array([0.70373239, 0.88803999, 0.33586594, 0.04267211, 0.51511206,
       0.28288743, 0.83196263, 0.82860846, 0.93169679, 0.7994458 ,
       0.78779557, 0.83559572, 0.91175693, 0.86101631, 0.7773911 ,
       0.75392228, 0.06309076, 0.35040148, 0.70982956, 0.29221985])

In [84]:
pd.cut(data,4,precision=2)

[(0.49, 0.71], (0.71, 0.93], (0.26, 0.49], (0.042, 0.26], (0.49, 0.71], ..., (0.71, 0.93], (0.042, 0.26], (0.26, 0.49], (0.71, 0.93], (0.26, 0.49]]
Length: 20
Categories (4, interval[float64, right]): [(0.042, 0.26] < (0.26, 0.49] < (0.49, 0.71] < (0.71, 0.93]]

In [85]:
data=np.random.standard_normal(1000)

In [86]:
data

array([ 8.08903959e-01, -5.02325484e-01, -9.08157196e-01,  1.55278642e+00,
        3.88689933e-01, -4.72820345e-02, -1.12940062e+00, -4.28368187e-01,
       -3.33360478e-01, -1.34440097e+00, -1.68669698e+00,  3.31768961e-01,
       -5.65776092e-01, -3.96454640e-01,  1.66613003e+00, -8.05780192e-01,
        2.42272239e-01, -2.20061919e+00, -1.77045388e-01, -3.02429100e-01,
        3.30287968e-01, -8.63116799e-01, -1.00464312e+00,  2.64533400e-01,
        1.94208357e-01, -2.43029964e-01,  8.32190615e-01,  8.53711223e-01,
       -1.83277283e-01, -8.49730197e-02,  1.15162083e+00, -2.32155357e-01,
        7.41576626e-01, -7.07951563e-01, -1.91471510e-01, -4.48721638e-02,
       -3.37909659e-01, -2.14567658e+00,  2.92043683e-01,  1.31845155e+00,
       -3.66526645e-01,  1.82272293e+00, -8.02154695e-01,  3.14685106e-01,
       -5.73966625e-01, -8.68028515e-01, -4.34920817e-02,  4.52129727e-01,
        8.12618281e-01, -6.82100533e-01,  1.26909563e+00,  5.86479556e-01,
       -4.27776192e-01, -6.57676757e-01, -9.27951501e-02, -4.62845516e-01,
        3.03911384e-01, -8.45117640e-01, -1.89574915e+00,  6.30998240e-01,
       -6.27066053e-01, -5.23680190e-01, -9.47742385e-01,  3.04671746e-01,
       -3.99636678e-02, -4.04327504e-01, -5.26221916e-01, -8.78639213e-01,
        4.45700190e-02, -8.10500135e-01,  2.46065100e-01, -1.08765252e+00,
       -9.82041368e-01,  2.16387361e-02,  1.78119563e-01,  9.91297419e-01,
       -1.09358096e+00, -2.32422285e-01, -9.84983801e-01,  1.26762903e+00,
        4.08771245e-01,  4.86611714e-01, -5.48287873e-01,  2.30372379e-01,
        1.21487021e+00, -8.92396698e-01,  6.05884149e-01, -1.98786195e-01,
       -1.81469285e-01,  2.82430100e-01,  2.48956620e-01,  1.95811179e-01,
        1.07762643e-01, -1.17434236e+00, -6.29464508e-01, -9.18228174e-01,
        3.66271463e-01,  1.31050448e+00,  3.00658925e-01,  2.53365081e-02,
        5.15464074e-01, -3.73472659e-01,  1.56191030e-01, -1.09530031e+00,
       -3.51478558e-01, -1.81420663e+00, -1.06743372e+00, -7.75581129e-01,
       -4.25762182e-01,  1.63788344e-01, -1.20408046e+00, -1.09620961e+00,
       -5.91207250e-01, -1.46461518e+00, -2.91318952e+00,  1.30142049e+00,
        8.09873263e-01,  1.34771067e+00, -1.22228925e+00, -8.30526104e-01,
       -8.72137771e-01,  5.54492440e-01,  3.70289026e-01, -1.26458298e-01,
        4.33857168e-02, -2.51313519e-02,  4.93807460e-02, -5.84573472e-01,
       -5.07250491e-01,  3.49283555e-01, -8.28795603e-01,  9.28357395e-01,
       -3.30427509e-01, -2.20204221e-01,  1.25568195e+00, -8.00900697e-01,
        2.15521590e-01, -2.15371483e-01, -1.96150135e+00,  1.99660974e-01,
       -4.33048486e-01,  9.62862355e-01,  5.44758137e-01,  4.37100618e-01,
        1.44712375e+00,  5.80316847e-01, -2.95316716e-01, -6.83471935e-02,
       -3.97938372e-01, -7.70327747e-02, -2.04784479e+00, -1.83856050e+00,
        6.49306087e-01,  1.31480453e+00, -2.33770233e-01,  4.96091543e-01,
       -1.38091314e-01, -1.31642254e+00,  2.59160282e-02, -2.85843275e-01,
       -1.95599984e-01,  1.12303835e-01, -2.77231965e-01,  1.61697794e+00,
       -1.75596026e-01, -1.21754729e-01,  2.05584501e-01,  2.54533356e+00,
       -1.13667106e+00, -2.06143967e+00, -1.27241144e-01, -7.83527809e-02,
       -2.35404368e+00, -1.40448208e-01,  4.23778308e-01, -1.81640444e-01,
       -9.24904886e-01, -4.26986808e-01, -4.35761964e-01,  4.35132524e-01,
        1.28690697e+00,  7.76605822e-01, -1.50645698e-01, -9.54111927e-01,
        8.00995383e-01,  1.31851219e-01, -1.37211521e+00,  1.98541828e+00,
       -2.77244715e-01,  6.84122879e-01,  2.48320546e-01,  1.43081933e+00,
        8.59883798e-01,  7.57830338e-01,  3.86648874e-01,  4.59500708e-01,
        8.06797656e-01, -2.05792007e-01, -1.77104123e-01,  9.01490038e-01,
        5.36276580e-01, -4.10015047e-01,  1.03211554e+00,  6.46015774e-01,
        2.78054009e-02, -3.99301172e-01,  1.19752923e+00,  4.84510206e-01,
       -7.04676871e-01, -6.16224491e-01, -2.29484274e+00,  9.31450787e-01,
       -1.56480081e+00,  9.94686079e-02, -9.40973922e-01,  4.82061595e-01,
        7.85054047e-01,  5.42056028e-01, -6.82836123e-01,  7.25380646e-01,
        1.39156325e+00,  2.60439382e-02, -5.03485615e-01,  1.17531726e+00,
        1.19773150e+00, -1.02979122e+00,  4.95158108e-01,  3.35582168e-01,
        7.26988384e-01,  1.64684981e+00, -2.50911607e+00, -1.47270199e+00,
        2.02158588e-01, -5.14925565e-02,  2.53139891e-01, -1.13580228e+00,
        5.55496985e-01, -5.95151652e-02, -2.22523599e+00, -1.82576031e+00,
        2.45045095e+00,  4.06539378e-01, -6.51154081e-01,  3.65738750e-01,
       -1.27644555e+00,  1.91995372e+00, -9.49829112e-01, -1.02406575e+00,
        9.48495014e-01,  1.67696305e+00,  1.03407708e+00, -6.97166235e-01,
        3.86061391e-01,  1.10676739e+00, -1.08620254e+00,  5.03169426e-02,
       -1.52396962e-01, -3.56657482e-01,  1.26013042e-01,  2.25767244e+00,
       -5.21399131e-01,  5.68572301e-01,  1.94383065e+00, -4.81095430e-01,
        2.61737596e-01,  2.34993112e+00, -2.08921844e-01,  3.25080455e-01,
        4.79722647e-01,  3.97237581e-01,  1.12143819e+00,  5.90998341e-01,
       -3.97891321e-01,  6.06548124e-01, -6.55490153e-01,  9.82049150e-01,
        6.25930005e-01, -9.46190729e-01, -1.07340266e+00,  2.02108154e-01,
        2.11200806e-01,  1.67162302e-01, -1.74623004e+00,  7.55134746e-01,
        7.33403657e-01,  8.26707525e-01,  3.22033170e-01,  1.27284039e+00,
       -3.72309211e-01, -1.27325044e+00,  4.36819742e-01,  6.68311644e-01,
        1.26432171e+00,  4.07875562e-01,  1.36668380e+00,  3.73611897e-01,
       -6.23944025e-01,  1.12448710e+00,  1.34265417e-01,  2.35056236e+00,
       -2.52189611e+00, -8.68485430e-01, -8.34927140e-01,  5.94541090e-01,
        6.44984920e-01,  9.88214533e-01, -6.87313872e-01,  1.08929854e+00,
        1.19530743e+00,  1.17952597e+00, -1.34334728e+00,  1.89750338e+00,
        4.97800322e-01,  1.39358500e+00, -1.74666128e-01, -9.45299325e-01,
        6.14354686e-01,  5.36436944e-01,  1.18828748e+00,  4.97034586e-01,
       -1.02225335e+00,  1.42658295e-01, -2.57759040e-01, -5.97260017e-02,
       -5.11422589e-01, -1.26350830e+00, -1.75233768e+00, -8.87638372e-01,
        5.39130813e-01, -4.79195466e-01,  2.91406951e+00, -1.92258975e-01,
        5.46866060e-01, -4.21747379e-01, -1.17666227e+00,  3.17515276e-01,
       -7.43687134e-01,  8.33886727e-01,  6.28235747e-01,  1.22892127e+00,
        6.79687670e-01,  1.09926568e-01, -7.36599905e-01,  1.14809497e+00,
       -1.64067556e-01,  1.74918855e+00,  5.59824136e-01,  9.01220533e-01,
       -1.89650647e-01,  2.37160961e-01,  1.81598940e+00,  9.14165070e-02,
        1.39833995e+00, -2.03711048e+00,  1.63115102e-01, -6.66226607e-02,
       -2.06237540e+00,  6.78567796e-01, -1.03675692e+00,  7.68267112e-01,
       -2.25792389e+00,  1.37072440e+00, -2.62713436e-01,  1.33881437e+00,
        1.61578616e-01,  7.48915887e-01, -1.50494846e-01,  1.14257275e+00,
       -1.07494140e+00, -3.63746950e-01,  1.27919717e-01,  6.02136493e-01,
        5.32007142e-01,  2.51863733e-01,  4.80458009e-01,  6.92045701e-01,
        1.75869181e-01, -1.30341606e-01,  8.76511674e-01,  5.50109525e-02,
       -9.36263360e-01,  6.85641271e-01, -6.77749457e-01,  7.78794840e-02,
       -2.82814413e-01, -1.10240378e+00, -5.14330303e-02, -6.66084782e-01,
       -7.19379502e-01, -5.82931888e-01,  3.86063616e-01,  4.99354190e-01,
        6.79852146e-01, -1.28151728e+00,  8.49739791e-01,  2.32399585e-01,
       -8.43774469e-01, -5.27416124e-01, -7.16405915e-02,  1.92618957e-01,
        1.77906582e-01,  2.05716239e+00,  7.51942934e-01, -3.89986612e-01,
        7.03746481e-01, -1.57657897e+00, -5.09761653e-02, -1.04826439e+00,
       -1.44112906e+00, -1.20016625e+00, -5.09394156e-01, -8.66110239e-02,
        4.56811884e-01,  2.09032015e+00, -1.42758948e+00,  1.62480579e+00,
        1.35243137e+00,  1.79119207e+00, -1.88334369e+00,  9.94647352e-01,
       -2.33368181e-01, -1.06154091e+00,  1.98345879e+00, -4.41641945e-01,
        3.81086907e-02, -2.68975965e-01,  6.91273656e-01, -1.61840379e+00,
        6.29767078e-01, -1.19075334e+00, -1.56094832e+00, -6.93600092e-01,
       -1.34378829e+00,  6.30845877e-01, -8.60831509e-01, -2.08876383e-01,
       -1.02332278e+00,  1.08280630e+00, -2.66823921e-01,  1.21610198e+00,
        2.04973208e-01, -1.09929031e+00,  1.01781464e+00,  8.42541323e-01,
       -1.15209654e+00,  1.03967221e-01,  8.85980807e-01, -1.92408686e-01,
       -1.95580814e+00,  2.17832870e-02, -5.99215997e-02,  1.45708547e-01,
       -2.54623057e-01, -1.03218953e+00, -2.68695895e-01,  1.83860532e-01,
       -4.29941175e-01, -2.11482352e+00, -5.02060774e-01,  2.20458273e-01,
       -1.52345929e+00,  7.72042675e-02,  1.02810862e+00,  3.75450152e-02,
        2.17433024e-01, -9.72048418e-01,  4.67723529e-01, -7.64559099e-01,
        3.50969943e-02,  6.40421877e-01,  2.43585779e-01,  8.15837398e-01,
        4.44713791e-01, -2.33830119e-01, -6.05368509e-01,  1.59510850e-01,
        6.05910423e-01, -7.85664876e-01, -1.28304932e-01,  4.16291074e-01,
        6.09797928e-01,  1.00004257e+00,  1.18535004e+00, -1.20122102e+00,
        5.08606104e-01,  3.52331370e-01, -1.57523178e+00, -1.20898286e+00,
        1.25773947e-01, -6.97945874e-01,  2.37176369e-01, -3.30227345e-01,
       -3.35066684e-01,  1.48429223e-01,  1.23258548e-01, -8.14355475e-01,
        1.37936847e+00,  6.49794313e-01,  5.43803823e-01,  1.33075939e+00,
        3.09655961e-01, -6.53230910e-02, -8.53741362e-01,  1.24338831e-01,
        1.58915247e+00, -9.87910146e-01,  2.61965612e-01, -6.95640429e-01,
       -1.10738022e-01,  1.62424986e+00,  9.11896985e-01, -6.83325786e-01,
       -2.49574791e-01,  7.16216841e-01,  3.41085700e+00, -8.24429096e-01,
        1.74979417e+00, -3.50378534e+00, -1.14444576e+00, -1.16154290e+00,
        1.26494146e-01, -7.93944538e-01,  7.97970322e-01,  6.86921163e-01,
        1.53216150e-01,  1.74744714e+00,  5.39920860e-01,  3.44842598e-01,
        4.42445016e-02,  3.83059657e-01, -8.49317833e-01,  2.13890603e-01,
        1.43931466e+00,  1.39900461e-01, -2.02321868e+00, -1.54683474e+00,
       -1.88073924e-01, -3.33027450e-01, -5.61802909e-01, -1.06188202e+00,
        9.61747051e-01, -4.89943438e-01, -1.00070100e+00, -8.63849826e-02,
       -1.64322697e+00,  1.15494835e+00,  1.66501337e+00,  3.74655284e-01,
        2.17212323e-01,  1.40065122e-01, -5.21272539e-01,  9.55791089e-01,
        3.61815523e-01,  6.01006692e-02, -1.22914432e-03, -1.02449051e+00,
        9.83515481e-01, -8.03528842e-01, -5.01597429e-01, -1.22693160e+00,
       -6.93413478e-01, -1.42159931e+00,  2.40242279e-02, -1.44489964e+00,
        1.93137230e-01,  1.91800337e-01, -3.44520180e-01, -8.01440658e-01,
        3.06101816e-01, -7.98436438e-02, -2.26741525e-01, -9.02938550e-01,
        7.62843899e-01,  1.16111422e+00, -6.46340965e-01, -2.08017409e-01,
       -9.25307270e-01,  9.98333179e-01, -6.02549071e-01,  3.50138419e-01,
        2.66635303e+00,  2.28428359e+00,  6.73278382e-01,  2.18884802e+00,
        7.06767935e-01,  8.98983792e-01, -1.74740165e-01,  3.22896517e-01,
        7.05602298e-01, -5.62607208e-01,  3.59625813e-01, -9.28291867e-01,
       -7.70545206e-02,  1.16365858e+00,  1.03632323e+00,  1.84742677e-01,
        9.32561626e-01, -4.13732781e-01, -1.86174877e-01,  9.76646129e-01,
        1.51476949e-01, -2.58284170e+00,  5.70799575e-01,  1.06855997e+00,
       -6.61688421e-02, -1.07632514e+00,  1.55827456e+00,  4.19808521e-01,
       -1.57908165e-01, -1.50063763e-01, -3.10814176e-01, -1.47632197e+00,
        2.35706168e+00,  4.36578984e-01, -5.50563092e-01,  6.89540861e-02,
        1.71250002e+00,  2.15719326e-01, -1.15528384e-01,  2.83824900e-01,
        3.66805477e-01, -4.56937904e-01,  4.41866366e-01, -1.99438786e-01,
       -1.03559208e+00, -1.05172811e+00,  6.38420268e-01, -7.60653372e-01,
       -1.69030327e+00, -3.43923352e-01, -8.37550581e-01, -2.57600180e+00,
        1.29014979e-01,  1.23460790e+00, -8.07300137e-01, -1.70331642e+00,
       -2.32919954e-01,  9.90186263e-01, -2.90940512e-01, -1.22623783e+00,
       -2.03868020e+00, -1.69657040e+00, -2.16786591e-01,  4.85939508e-02,
        1.66490876e+00,  7.66992223e-01, -4.63174864e-01,  2.00457378e-01,
       -6.66866276e-01, -4.66460483e-01,  1.81515866e-01, -1.02697165e+00,
        6.12810439e-01,  1.29933114e+00, -6.74091579e-01, -2.23866091e-01,
        9.77216824e-01,  1.53162716e+00, -6.47200506e-01, -4.77328061e-02,
       -1.05311437e+00, -1.21965605e+00, -8.86549500e-01, -3.08681360e-01,
        1.83382667e-01, -1.54308101e-01,  9.04039367e-01, -7.48814850e-01,
       -9.11737774e-02,  4.20891239e-01, -8.03434541e-01, -1.36618784e+00,
       -1.13173916e+00, -1.88957062e+00, -8.27647134e-01, -9.62404069e-01,
        1.20036045e+00, -3.73379159e-01,  3.30471629e-01, -5.77479933e-01,
       -5.08623320e-01, -9.79666707e-02,  3.46819601e-01,  1.34157696e+00,
       -1.21344112e+00,  9.03950858e-01, -8.06570001e-02, -6.07836457e-01,
       -1.70192404e+00, -1.40660414e+00,  5.54944153e-01, -7.88627303e-01,
        5.08580064e-01,  3.38429990e-01,  1.69746784e-01, -1.18355310e-01,
       -2.01309459e+00, -7.57265813e-01, -6.63698201e-01, -2.40591960e+00,
        1.19153045e-01,  2.20576353e+00, -6.63852820e-02,  1.28179152e+00,
       -4.66471295e-01,  2.11617348e+00,  7.73984054e-01,  1.40799255e+00,
       -1.54751456e+00,  2.40058334e-01,  1.72185117e-01, -1.59967545e+00,
        1.10384085e+00,  2.60079805e-01, -2.88328063e-02, -2.02605357e-02,
       -5.89922722e-02,  5.82485172e-01,  1.22687166e-01, -2.14836681e-01,
       -3.62277833e-01, -5.47505832e-01, -7.47654874e-01, -4.12451456e-01,
        4.25249838e-01, -1.89216308e-01,  4.59025681e-01, -9.15189931e-01,
        1.31116533e+00,  1.20431290e+00, -1.23086937e+00, -1.11502608e-01,
        1.04125191e-01,  5.90696371e-01, -1.51623617e+00,  1.78055542e+00,
       -1.41880776e-01, -1.46856467e+00,  3.59964424e-01, -7.74328782e-02,
        1.03611990e+00,  1.17138718e-01,  1.50040859e-01, -1.27941241e+00,
       -6.29652433e-01, -3.76645083e-01, -1.39775700e+00,  1.01982926e+00,
       -1.30682329e+00,  7.18685587e-01,  3.15331379e-01, -4.41623374e-01,
       -2.32717846e+00, -1.47235320e+00, -7.99807391e-01,  1.05659743e+00,
        1.41648320e+00, -1.97792077e+00,  1.55381708e+00,  2.63754383e-01,
        3.62706891e-01, -2.08948576e-02,  1.16508336e-02, -5.42106157e-01,
        1.03874646e+00, -1.39498880e+00,  4.56383580e-01,  1.86287806e+00,
        1.28906435e+00, -8.72558145e-01, -3.67980461e-01, -1.83420228e-01,
        1.12992682e+00, -3.46500185e-01, -2.32487585e-01, -1.02510999e+00,
        3.83409245e-01,  3.15642014e-01,  6.20022913e-01,  1.68285127e+00,
       -1.81008217e+00,  9.96837423e-01, -1.09143334e+00, -1.49837870e-01,
        2.45045294e+00, -1.97514456e+00,  1.07621734e+00, -9.40317396e-01,
        7.92233498e-01, -3.39781165e-03, -9.99860522e-01, -1.53421840e+00,
       -3.45345627e-01,  1.04698626e+00,  2.57527483e-01,  6.14223039e-01,
        3.63025474e-01,  1.22545988e+00,  9.95254828e-01,  1.41406679e+00,
        7.28776889e-01, -1.04191021e+00,  1.12065880e+00, -1.13751428e+00,
       -3.43518528e-01,  1.02963498e+00, -2.41103375e-01,  1.17437053e+00,
        8.87621055e-01, -7.86580562e-01, -7.56189484e-01, -9.31548256e-01,
        8.26810981e-01, -1.78244724e+00, -9.32267185e-02, -2.32345398e-01,
        1.17296173e+00,  1.89227636e-01,  2.10707894e-01,  1.29457244e+00,
        5.96728457e-01, -7.22383086e-01, -2.54669568e-01, -7.27759586e-01,
       -9.33757532e-01, -6.51176938e-01,  1.37093883e+00, -1.12358952e+00,
       -2.01824885e+00, -1.63827155e-01,  1.26258151e+00,  2.41245740e+00,
        7.64354100e-01, -1.01625451e+00, -8.96557018e-01,  3.30225818e-01,
        1.19984082e+00,  1.30361953e+00, -7.04516231e-01, -1.28164819e-01,
       -1.20797388e-01, -3.50149201e-01, -7.48006900e-01,  2.44933690e-01,
       -1.09003889e-01,  4.01013784e-02, -1.57363772e+00,  1.36176512e+00,
        3.82464523e-01, -9.39734034e-01, -1.53384029e+00, -1.24570625e+00,
       -1.09376969e+00,  2.36140944e+00,  1.61977305e+00,  1.16803855e+00,
       -4.80906216e-01,  1.76678354e-01, -1.24405996e+00,  1.75294750e+00,
       -2.20597974e-01,  4.85460761e-01,  4.90927827e-01, -2.50020995e-01,
        4.08210557e-03, -1.99665272e-02, -6.16796546e-01,  1.98010207e+00,
       -1.22967924e+00,  1.99795356e-01,  1.39934100e+00, -9.23099592e-01,
        7.05083353e-01, -2.84710079e-01,  1.33291461e+00, -7.47908710e-01,
        5.38102912e-01,  4.61542621e-01, -1.37190807e-01, -3.57441015e-01,
       -1.15199306e+00,  1.39069972e+00,  1.02784650e+00, -5.65900202e-01,
       -2.52046483e-01,  1.45741370e+00, -5.71156141e-01,  3.09786997e-01,
        1.68154614e+00,  2.30650910e-01, -4.14216217e-01, -1.54688041e+00,
        6.16367859e-01,  1.47925845e+00, -1.24161245e+00, -8.32967881e-01,
        7.40804408e-01,  1.06122903e+00, -4.87188643e-01, -1.48493767e+00,
       -1.21079577e-01,  1.96158387e+00, -1.76578363e+00,  2.83486738e-01,
       -2.64977860e-01, -1.79400838e+00, -9.90116635e-01, -8.17384513e-01,
       -2.81375389e-02,  3.90938394e-01,  1.01145563e+00,  6.39797430e-01,
        1.06116644e+00,  1.26262755e+00, -8.49741352e-01, -3.84467575e-01,
       -2.67102049e+00, -4.25378078e-01, -8.50821276e-01,  6.08603875e-02,
        9.40257650e-01,  1.20816753e+00,  8.51998367e-01,  6.46415589e-01,
       -9.26670758e-01, -6.12993858e-01, -1.38636544e+00,  9.30483899e-02,
        7.76910856e-01,  6.95125584e-01,  7.23074829e-01,  1.84334117e-01,
        1.53606044e-01,  1.00430945e-01,  8.45441615e-01, -8.73509764e-01,
        4.04411359e-01,  1.72312640e-01, -1.72234557e+00,  3.69056467e-01,
       -1.99590265e-01,  6.98465892e-01, -2.16783545e-01,  1.41110567e+00,
       -8.87212435e-01,  7.94568542e-01, -1.05068880e+00, -8.81324807e-01,
        2.48778075e-01, -1.67112621e+00, -7.37674069e-01, -9.61700427e-01,
        7.07024816e-01,  1.65994323e+00, -4.61493406e-01, -2.77087649e-01,
       -1.52026265e+00, -7.30670435e-01, -6.09168725e-01, -5.17462147e-01,
       -1.18978918e+00,  1.06512439e+00,  3.99609841e-01,  3.17723255e-01,
       -1.18405434e+00,  7.46283833e-01,  6.70205320e-01,  1.07717524e+00,
        5.60720005e-01,  1.56466368e+00,  1.06885521e-01, -3.77649675e-01,
        4.23351104e-01,  1.67801802e+00,  3.14865124e-01, -8.49045189e-01,
       -2.47492069e-01, -8.79831108e-01, -9.33844370e-02, -9.77389541e-01,
        6.55366169e-01,  1.00502773e+00,  7.36075225e-01,  2.15068427e+00,
        6.68634402e-01,  1.43843058e-02, -1.95115865e-01, -9.39888984e-01,
       -1.21576100e+00, -1.50417993e+00, -4.39832530e-01, -4.40877256e-01,
        8.61453537e-01,  1.06568515e+00,  6.04643048e-01, -2.88219058e-01,
       -3.13070054e+00, -9.39347798e-01, -8.41410786e-01,  3.66769534e-01])

In [87]:
quartiles=pd.qcut(data,4,precision=2)

In [88]:
quartiles

[(0.64, 3.41], (-0.7, 0.0014], (-3.51, -0.7], (0.64, 3.41], (0.0014, 0.64], ..., (-0.7, 0.0014], (-3.51, -0.7], (-3.51, -0.7], (-3.51, -0.7], (0.0014, 0.64]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.51, -0.7] < (-0.7, 0.0014] < (0.0014, 0.64] < (0.64, 3.41]]

In [89]:
pd.value_counts(quartiles)

C:\Users\Prathamesh Gawas\AppData\Local\Temp\ipykernel_24312\3472704981.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(quartiles)

(-3.51, -0.7]     250
(-0.7, 0.0014]    250
(0.0014, 0.64]    250
(0.64, 3.41]      250
Name: count, dtype: int64

In [90]:
pd.qcut(data,[0,0.1,0.5,0.9,1]).value_counts()

(-3.505, -1.216]     100
(-1.216, 0.00143]    400
(0.00143, 1.226]     400
(1.226, 3.411]       100
Name: count, dtype: int64


# Detecting and Filtering Outliers

In [91]:
data=pd.DataFrame(np.random.standard_normal((1000,4)))

In [92]:
data

            0         1         2         3
0    0.989518  0.243954  0.247092 -1.417544
1    0.681943  0.028620 -1.133340  0.144116
2   -0.193637  0.245340 -0.146885 -0.012727
3   -0.603742  1.559842 -0.505120 -0.477576
4    0.441656 -0.989610 -1.180793  2.962571
..        ...       ...       ...       ...
995 -0.691400  0.147052  1.489181  0.465395
996 -1.262977 -1.566291 -0.846948 -0.538210
997 -0.815114 -1.220448 -1.205677  1.875688
998 -0.041152  1.979797 -0.257280  0.314373
999  0.452949 -0.158998  0.073784 -1.568842

[1000 rows x 4 columns]

In [93]:
data.describe()

                 0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.019045     0.040525    -0.048743     0.018408
std       0.986463     1.021917     1.002567     0.966511
min      -2.783124    -3.457605    -3.089797    -2.975454
25%      -0.655768    -0.639816    -0.781294    -0.610209
50%       0.035498     0.038485    -0.052900    -0.000007
75%       0.652558     0.735262     0.600370     0.635452
max       3.312641     3.756906     4.030953     2.962571

In [94]:
col=data[2]

In [95]:
col

0      0.247092
1     -1.133340
2     -0.146885
3     -0.505120
4     -1.180793
         ...
995    1.489181
996   -0.846948
997   -1.205677
998   -0.257280
999    0.073784
Name: 2, Length: 1000, dtype: float64

In [96]:
col[col.abs()>3]

10     3.328144
192   -3.089797
257    4.030953
761    3.851733
Name: 2, dtype: float64

In [97]:
data[(data.abs()>3).any(axis="columns")]

            0         1         2         3
10  -0.491681  0.059264  3.328144  0.407643
177  3.312641 -0.510266 -0.181156  0.715168
192 -0.699454 -0.717582 -3.089797 -0.409120
257 -0.200922  1.256970  4.030953  1.019986
296 -0.616944 -3.457605 -0.913820 -0.867903
761 -0.160416  1.427083  3.851733 -0.472973
919 -0.264064  3.756906  0.898701 -1.171849

In [98]:
np.sign(data)*3

       0    1    2    3
0    3.0  3.0  3.0 -3.0
1    3.0  3.0 -3.0  3.0
2   -3.0  3.0 -3.0 -3.0
3   -3.0  3.0 -3.0 -3.0
4    3.0 -3.0 -3.0  3.0
..   ...  ...  ...  ...
995 -3.0  3.0  3.0  3.0
996 -3.0 -3.0 -3.0 -3.0
997 -3.0 -3.0 -3.0  3.0
998 -3.0  3.0 -3.0  3.0
999  3.0 -3.0  3.0 -3.0

[1000 rows x 4 columns]

In [99]:
data[data.abs()>3]=np.sign(data)*3

In [100]:
data.describe()

                 0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.018732     0.040225    -0.050864     0.018408
std       0.985467     1.017969     0.994588     0.966511
min      -2.783124    -3.000000    -3.000000    -2.975454
25%      -0.655768    -0.639816    -0.781294    -0.610209
50%       0.035498     0.038485    -0.052900    -0.000007
75%       0.652558     0.735262     0.600370     0.635452
max       3.000000     3.000000     3.000000     2.962571

In [101]:
np.sign(data).head()

     0    1    2    3
0  1.0  1.0  1.0 -1.0
1  1.0  1.0 -1.0  1.0
2 -1.0  1.0 -1.0 -1.0
3 -1.0  1.0 -1.0 -1.0
4  1.0 -1.0 -1.0  1.0

# Permutation and Random Sampling

In [102]:
df=pd.DataFrame(np.arange(5*7).reshape((5,7)))

In [103]:
df

    0   1   2   3   4   5   6
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
2  14  15  16  17  18  19  20
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34

In [104]:
sampler=np.random.permutation(5)

In [105]:
sampler

array([1, 3, 4, 2, 0], dtype=int32)

In [106]:
df.take(sampler)

    0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34
2  14  15  16  17  18  19  20
0   0   1   2   3   4   5   6

In [107]:
df.iloc[sampler]

    0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34
2  14  15  16  17  18  19  20
0   0   1   2   3   4   5   6

In [108]:
columnn_sampler=np.random.permutation(7)

In [109]:
columnn_sampler

array([6, 3, 0, 1, 5, 2, 4], dtype=int32)

In [110]:
df.take(columnn_sampler,axis="columns")

    6   3   0   1   5   2   4
0   6   3   0   1   5   2   4
1  13  10   7   8  12   9  11
2  20  17  14  15  19  16  18
3  27  24  21  22  26  23  25
4  34  31  28  29  33  30  32

In [111]:
df

    0   1   2   3   4   5   6
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
2  14  15  16  17  18  19  20
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34

In [112]:
df.sample(n=3)

    0   1   2   3   4   5   6
3  21  22  23  24  25  26  27
1   7   8   9  10  11  12  13
0   0   1   2   3   4   5   6

In [113]:
choices=pd.Series([5,7,-1,6,4])

In [114]:
choices

0    5
1    7
2   -1
3    6
4    4
dtype: int64

In [115]:
choices.sample(n=10,replace=True)

1    7
2   -1
4    4
4    4
2   -1
0    5
0    5
2   -1
2   -1
3    6
dtype: int64

Computing Indicator/Dummy Variables

In [116]:
df=pd.DataFrame({
    "key":list("bbacab"),
    "data1":range(6)
})

In [117]:
df

  key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [118]:
pd.get_dummies(df["key"])

       a      b      c
0  False   True  False
1  False   True  False
2   True  False  False
3  False  False   True
4   True  False  False
5  False   True  False

In [119]:
dummies=pd.get_dummies(df["key"],prefix="key")

In [120]:
dummies

   key_a  key_b  key_c
0  False   True  False
1  False   True  False
2   True  False  False
3  False  False   True
4   True  False  False
5  False   True  False

In [121]:
df_with_dummy=df[["data1"]].join(dummies)

In [122]:
df_with_dummy

   data1  key_a  key_b  key_c
0      0  False   True  False
1      1  False   True  False
2      2   True  False  False
3      3  False  False   True
4      4   True  False  False
5      5  False   True  False

In [123]:
mnames = ["movie_id", "title", "genres"]

In [124]:
movies=pd.read_table("datasets/movielens/movies.dat",sep="::",header=None,names=mnames,engine="python")

In [125]:
movies.head()

   movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy

In [126]:
dummies=movies["genres"].str.get_dummies("|")

In [127]:
dummies.iloc[:10,:6]

   Action  Adventure  Animation  Children's  Comedy  Crime
0       0          0          1           1       1      0
1       0          1          0           1       0      0
2       0          0          0           0       1      0
3       0          0          0           0       1      0
4       0          0          0           0       1      0
5       1          0          0           0       0      1
6       0          0          0           0       1      0
7       0          1          0           1       0      0
8       1          0          0           0       0      0
9       1          1          0           0       0      0

In [128]:
movies_windic=movies.join(dummies.add_prefix("Genre_"))

In [129]:
movies_windic.iloc[0]

movie_id                                       1
title                           Toy Story (1995)
genres               Animation|Children's|Comedy
Genre_Action                                   0
Genre_Adventure                                0
Genre_Animation                                1
Genre_Children's                               1
Genre_Comedy                                   1
Genre_Crime                                    0
Genre_Documentary                              0
Genre_Drama                                    0
Genre_Fantasy                                  0
Genre_Film-Noir                                0
Genre_Horror                                   0
Genre_Musical                                  0
Genre_Mystery                                  0
Genre_Romance                                  0
Genre_Sci-Fi                                   0
Genre_Thriller                                 0
Genre_War                                      0
Genre_Western                                  0
Name: 0, dtype: object

In [130]:
np.random.seed(12345)

In [131]:
values=np.random.uniform(size=10)

In [132]:
values

array([0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503,
       0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987])

In [133]:
bins=[0,0.2,0.4,0.6,0.8,1]

In [134]:
pd.cut(values,bins)

[(0.8, 1.0], (0.2, 0.4], (0.0, 0.2], (0.2, 0.4], (0.4, 0.6], (0.4, 0.6], (0.8, 1.0], (0.6, 0.8], (0.6, 0.8], (0.6, 0.8]]
Categories (5, interval[float64, right]): [(0.0, 0.2] < (0.2, 0.4] < (0.4, 0.6] < (0.6, 0.8] < (0.8, 1.0]]

In [135]:
pd.get_dummies(pd.cut(values,bins))

   (0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0       False       False       False       False        True
1       False        True       False       False       False
2        True       False       False       False       False
3       False        True       False       False       False
4       False       False        True       False       False
5       False       False        True       False       False
6       False       False       False       False        True
7       False       False       False        True       False
8       False       False       False        True       False
9       False       False       False        True       False

7.3 Extension Data Types

In [136]:
s=pd.Series([1,2,3,None])

In [137]:
s

0    1.0
1    2.0
2    3.0
3    NaN
dtype: float64

In [138]:
s.dtype

dtype('float64')

In [139]:
s=pd.Series([1,2,3,None],dtype=pd.Int64Dtype())

In [140]:
s

0       1
1       2
2       3
3    <NA>
dtype: Int64

In [141]:
s.isna()

0    False
1    False
2    False
3     True
dtype: bool

In [142]:
s[3]

In [143]:
s[3] is pd.NA

True

In [144]:
s=pd.Series([1,2,3,None],dtype="Int64")

In [145]:
s

0       1
1       2
2       3
3    <NA>
dtype: Int64

In [146]:
s=pd.Series(["one","two",None,"three"],dtype=pd.StringDtype())

In [147]:
s

0      one
1      two
2     <NA>
3    three
dtype: string

In [148]:
dict={
    "A":[1,2,None,4],
    "B":["one","two","three",None],
    "C":[False,None,False,True]
}

In [149]:
df=pd.DataFrame(dict)

In [150]:
df

     A      B      C
0  1.0    one  False
1  2.0    two   None
2  NaN  three  False
3  4.0   None   True

In [151]:
df["A"]=df["A"].astype("Int64")

In [152]:
df["B"]=df["B"].astype("string")

In [153]:
df["C"]=df["C"].astype("boolean")

In [154]:
df

      A      B      C
0     1    one  False
1     2    two   <NA>
2  <NA>  three  False
3     4   <NA>   True

## Table 7-3. pandas extension data types

| Extension type   | Description                                                                 | Example (Python) |
|------------------|-----------------------------------------------------------------------------|------------------|
| `BooleanDtype`   | Nullable Boolean data, use `"boolean"` when passing as string               | `pd.Series([True, False, None], dtype="boolean")` |
| `CategoricalDtype` | Categorical data type, use `"category"` when passing as string            | `pd.Series(["a","b","a"], dtype="category")` |
| `DatetimeTZDtype` | Datetime with time zone                                                    | `pd.Series(pd.date_range("2024-01-01", periods=3, tz="UTC"))` |
| `Float32Dtype`   | 32-bit nullable floating point, use `"Float32"` when passing as string      | `pd.Series([1.0, None, 3.5], dtype="Float32")` |
| `Float64Dtype`   | 64-bit nullable floating point, use `"Float64"` when passing as string      | `pd.Series([1.0, None, 3.5], dtype="Float64")` |
| `Int8Dtype`      | 8-bit nullable signed integer, use `"Int8"` when passing as string          | `pd.Series([1, None, 3], dtype="Int8")` |
| `Int16Dtype`     | 16-bit nullable signed integer, use `"Int16"` when passing as string        | `pd.Series([1, None, 3], dtype="Int16")` |
| `Int32Dtype`     | 32-bit nullable signed integer, use `"Int32"` when passing as string        | `pd.Series([1, None, 3], dtype="Int32")` |
| `Int64Dtype`     | 64-bit nullable signed integer, use `"Int64"` when passing as string        | `pd.Series([1, None, 3], dtype="Int64")` |
| `UInt8Dtype`     | 8-bit nullable unsigned integer, use `"UInt8"` when passing as string       | `pd.Series([1, None, 3], dtype="UInt8")` |
| `UInt16Dtype`    | 16-bit nullable unsigned integer, use `"UInt16"` when passing as string     | `pd.Series([1, None, 3], dtype="UInt16")` |
| `UInt32Dtype`    | 32-bit nullable unsigned integer, use `"UInt32"` when passing as string     | `pd.Series([1, None, 3], dtype="UInt32")` |
| `UInt64Dtype`    | 64-bit nullable unsigned integer, use `"UInt64"` when passing as string     | `pd.Series([1, None, 3], dtype="UInt64")` |

# 7.4 String Manipulation

In [155]:
val="a,b, guido"

In [156]:
val.split(",")

['a', 'b', ' guido']

In [157]:
pieces=[x.strip() for x in val.split(",")]

In [158]:
pieces

['a', 'b', 'guido']

In [159]:
first,second,third=pieces

In [160]:
first + "::"+ second +"::"+third

'a::b::guido'

In [161]:
"::".join(pieces)

'a::b::guido'

In [162]:
"guido" in val

True

In [163]:
val

'a,b, guido'

In [164]:
val.index(",")

1

In [165]:
val.find(":")

-1

In [166]:
val.index(":")

ValueError: substring not found

In [ ]:
val.count(",")

2

In [ ]:
val.replace(",","::")

'a::b:: guido'

In [ ]:
val.replace(",","")

'ab guido'

## Common Python String Methods

| Method        | Description                                                                 | Example (Python) | Output |
|---------------|-----------------------------------------------------------------------------|------------------|--------|
| `count`       | Return the number of nonoverlapping occurrences of substring in the string  | `"banana".count("a")` | `3` |
| `endswith`    | Return True if string ends with suffix                                      | `"hello".endswith("lo")` | `True` |
| `startswith`  | Return True if string starts with prefix                                    | `"hello".startswith("he")` | `True` |
| `join`        | Use string as delimiter for concatenating a sequence of other strings       | `",".join(["a","b","c"])` | `"a,b,c"` |
| `index`       | Return starting index of first occurrence of substring; raises `ValueError` if not found | `"hello".index("e")` | `1` |
| `find`        | Return position of first occurrence of substring; returns `-1` if not found | `"hello".find("x")` | `-1` |
| `rfind`       | Return position of last occurrence of substring; returns `-1` if not found  | `"banana".rfind("a")` | `5` |
| `replace`     | Replace occurrences of substring with another string                       | `"hello world".replace("world","Python")` | `"hello Python"` |
| `strip`       | Trim whitespace/newlines on both sides                                     | `"  hello  ".strip()` | `"hello"` |
| `rstrip`      | Trim whitespace/newlines on the right side                                 | `"hello   ".rstrip()` | `"hello"` |
| `lstrip`      | Trim whitespace/newlines on the left side                                  | `"   hello".lstrip()` | `"hello"` |
| `split`       | Break string into list of substrings using delimiter                       | `"a,b,c".split(",")` | `["a","b","c"]` |
| `lower`       | Convert alphabet characters to lowercase                                   | `"HELLO".lower()` | `"hello"` |
| `upper`       | Convert alphabet characters to uppercase                                   | `"hello".upper()` | `"HELLO"` |
| `casefold`    | Convert to lowercase, handling region-specific variations for comparison   | `"ß".casefold()` | `"ss"` |
| `ljust`       | Left justify string, padding right side with spaces or fill character      | `"hi".ljust(5,"-")` | `"hi---"` |
| `rjust`       | Right justify string, padding left side with spaces or fill character      | `"hi".rjust(5,"-")` | `"---hi"` |

Regular Expressions

In [ ]:
import re

In [ ]:
text="foo bar\t baz \tqux"

In [ ]:
re.split(r"\s+",text)

['foo', 'bar', 'baz', 'qux']

In [ ]:
regex=re.compile(r"\s+")

In [ ]:
regex.split(text)

['foo', 'bar', 'baz', 'qux']

In [ ]:
regex.findall(text)

[' ', '\t ', ' \t']

In [ ]:
text = """Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com"""
pattern = r"[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}"

In [ ]:
regex=re.compile(pattern,flags=re.IGNORECASE)

In [ ]:
regex.findall(text)

['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'ryan@yahoo.com']

In [ ]:
m=regex.search(text)

In [ ]:
m

In [ ]:
text[m.start():m.end()]

'dave@google.com'

In [ ]:
print(regex.match(text))

None

In [ ]:
print(regex.sub("REDACTED",text))

Dave REDACTED
Steve REDACTED
Rob REDACTED
Ryan REDACTED

In [ ]:
pattern = r"([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})"

In [ ]:
regex=re.compile(pattern,flags=re.IGNORECASE)

In [ ]:
m=regex.match("wesm@bright.net")

In [ ]:
m.groups()

('wesm', 'bright', 'net')

In [ ]:
text

'Dave dave@google.com\nSteve steve@gmail.com\nRob rob@gmail.com\nRyan ryan@yahoo.com'

In [ ]:
regex.findall(text)

[('dave', 'google', 'com'),
 ('steve', 'gmail', 'com'),
 ('rob', 'gmail', 'com'),
 ('ryan', 'yahoo', 'com')]

In [ ]:
print(regex.sub(r"Username:\1, Domain:\2, Suffix:\3",text))

Dave Username:dave, Domain:google, Suffix:com
Steve Username:steve, Domain:gmail, Suffix:com
Rob Username:rob, Domain:gmail, Suffix:com
Ryan Username:ryan, Domain:yahoo, Suffix:com

## Common `re` (regular expression) methods in Python

| Method      | Description                                                                 | Example (Python) | Output |
|-------------|-----------------------------------------------------------------------------|------------------|--------|
| `findall`   | Return all nonoverlapping matching patterns in a string as a list           | `re.findall(r"\d+", "abc123def45")` | `['123','45']` |
| `finditer`  | Like `findall`, but returns an iterator yielding match objects              | `[m.group() for m in re.finditer(r"\d+", "abc123def45")]` | `['123','45']` |
| `match`     | Match pattern at start of string; returns a match object or `None`          | `re.match(r"\d+", "123abc")` | `<Match '123'>` |
| `search`    | Scan string for match; returns first match object (anywhere in string)      | `re.search(r"\d+", "abc123def")` | `<Match '123'>` |
| `split`     | Break string into pieces at each occurrence of pattern                      | `re.split(r"\d+", "abc123def45ghi")` | `['abc','def','ghi']` |
| `sub`       | Replace all occurrences of pattern with replacement string                  | `re.sub(r"\d+", "#", "abc123def45")` | `"abc#def#"` |
| `subn`      | Like `sub`, but also return number of substitutions made                    | `re.subn(r"\d+", "#", "abc123def45")` | `('abc#def#', 2)` |

String Functions in pandas

In [ ]:
data = {"Dave": "dave@google.com", "Steve": "steve@gmail.com",     
"Rob": "rob@gmail.com", "Wes": np.nan}

In [ ]:
data=pd.Series(data)

In [ ]:
data

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object

In [ ]:
data.isna()

Dave     False
Steve    False
Rob      False
Wes       True
dtype: bool

In [ ]:
data.str.contains("gmail")

Dave     False
Steve     True
Rob       True
Wes        NaN
dtype: object

In [ ]:
data_as_string_ext=data.astype("string")

In [ ]:
data_as_string_ext

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                 <NA>
dtype: string

In [ ]:
data_as_string_ext.str.contains("gmail")

Dave     False
Steve     True
Rob       True
Wes       <NA>
dtype: boolean

In [ ]:
pattern = r"([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})"

In [ ]:
import re

In [ ]:
data.str.findall(pattern,flags=re.IGNORECASE)

Dave     [(dave, google, com)]
Steve    [(steve, gmail, com)]
Rob        [(rob, gmail, com)]
Wes                        NaN
dtype: object

In [ ]:
matches=data.str.findall(pattern,flags=re.IGNORECASE).str[0]

In [ ]:
matches

Dave     (dave, google, com)
Steve    (steve, gmail, com)
Rob        (rob, gmail, com)
Wes                      NaN
dtype: object

In [ ]:
matches.str.get(1)

Dave     google
Steve     gmail
Rob       gmail
Wes         NaN
dtype: object

In [ ]:
data

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object

In [ ]:
data.str[:5]

Dave     dave@
Steve    steve
Rob      rob@g
Wes        NaN
dtype: object

In [ ]:
data.str.extract(pattern,flags=re.IGNORECASE)

           0       1    2
Dave    dave  google  com
Steve  steve   gmail  com
Rob      rob   gmail  com
Wes      NaN     NaN  NaN

## Common Pandas `.str` string methods

| Method       | Description                                                                 | Example (Python) | Output |
|--------------|-----------------------------------------------------------------------------|------------------|--------|
| `cat`        | Concatenate strings element-wise with optional delimiter                   | `s.str.cat(sep=",")` | `"a,b,c"` |
| `contains`   | Return Boolean array if each string contains pattern/regex                 | `s.str.contains("foo")` | `[True, False, ...]` |
| `count`      | Count occurrences of pattern                                               | `s.str.count("a")` | `[2, 0, ...]` |
| `extract`    | Use regex groups to extract substrings; returns DataFrame                  | `s.str.extract(r"(\d+)")` | `[['123'], ['45']]` |
| `endswith`   | Equivalent to `x.endswith(pattern)` for each element                       | `s.str.endswith("txt")` | `[True, False, ...]` |
| `startswith` | Equivalent to `x.startswith(pattern)` for each element                     | `s.str.startswith("pre")` | `[True, False, ...]` |
| `findall`    | Compute list of all occurrences of pattern/regex for each string           | `s.str.findall(r"\d+")` | `[['123','45'], ['67']]` |
| `get`        | Index into each element (retrieve i-th character)                          | `s.str.get(0)` | First character of each string |
| `isalnum`    | Equivalent to built-in `str.isalnum`                                       | `s.str.isalnum()` | `[True, False, ...]` |
| `isalpha`    | Equivalent to built-in `str.isalpha`                                       | `s.str.isalpha()` | `[True, False, ...]` |
| `isdecimal`  | Equivalent to built-in `str.isdecimal`                                     | `s.str.isdecimal()` | `[True, False, ...]` |
| `isdigit`    | Equivalent to built-in `str.isdigit`                                       | `s.str.isdigit()` | `[True, False, ...]` |
| `islower`    | Equivalent to built-in `str.islower`                                       | `s.str.islower()` | `[True, False, ...]` |
| `isnumeric`  | Equivalent to built-in `str.isnumeric`                                     | `s.str.isnumeric()` | `[True, False, ...]` |
| `isupper`    | Equivalent to built-in `str.isupper`                                       | `s.str.isupper()` | `[True, False, ...]` |
| `join`       | Join strings in each element with passed separator                         | `s.str.join("-")` | `"a-b-c"` |
| `len`        | Compute length of each string                                              | `s.str.len()` | `[5, 3, ...]` |
| `lower`      | Convert to lowercase                                                       | `s.str.lower()` | `"hello"` |
| `upper`      | Convert to uppercase                                                       | `s.str.upper()` | `"HELLO"` |
| `match`      | Apply `re.match` to each element; returns True/False                       | `s.str.match(r"^\d+")` | `[True, False, ...]` |
| `pad`        | Add whitespace to left, right, or both sides                               | `s.str.pad(10, side="right")` | `"abc       "` |
| `center`     | Equivalent to `pad(side="both")`                                           | `s.str.center(10)` | `"   abc    "` |
| `repeat`     | Duplicate values (like `x * n`)                                            | `s.str.repeat(3)` | `"abcabcabc"` |
| `replace`    | Replace occurrences of pattern/regex with another string                   | `s.str.replace("foo","bar")` | `"bar"` |
| `slice`      | Slice each string in the Series                                            | `s.str.slice(0,3)` | `"abc"` |
| `split`      | Split strings on delimiter or regex                                        | `s.str.split(",")` | `[['a','b','c'], ...]` |
| `strip`      | Trim whitespace/newlines from both sides                                   | `s.str.strip()` | `"hello"` |
| `rstrip`     | Trim whitespace/newlines from right side                                   | `s.str.rstrip()` | `"hello"` |
| `lstrip`     | Trim whitespace/newlines from left side                                    | `s.str.lstrip()` | `"hello"` |

# 7.5 Categorical Data

In [ ]:
values=pd.Series(["apple",'orange',"apple","apple"]*2)

In [ ]:
values

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
dtype: object

In [ ]:
pd.unique(values)

array(['apple', 'orange'], dtype=object)

In [ ]:
pd.value_counts(values)

C:\Users\Prathamesh Gawas\AppData\Local\Temp\ipykernel_31108\3297668723.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(values)

apple     6
orange    2
Name: count, dtype: int64

In [ ]:
values=pd.Series([0,1,0,0]*2)

In [ ]:
dim=pd.Series(["apple","orange"])

In [ ]:
values

0    0
1    1
2    0
3    0
4    0
5    1
6    0
7    0
dtype: int64

In [ ]:
dim

0     apple
1    orange
dtype: object

In [ ]:
dim.take(values)

0     apple
1    orange
0     apple
0     apple
0     apple
1    orange
0     apple
0     apple
dtype: object

Categorical Extension Type in pandas

In [ ]:
fruits=["apple","orange","apple","apple"]*2

In [ ]:
fruits

['apple', 'orange', 'apple', 'apple', 'apple', 'orange', 'apple', 'apple']

In [ ]:
N=len(fruits)

In [ ]:
rng=np.random.default_rng(seed=12345)

In [ ]:
rng

Generator(PCG64) at 0x24D733451C0

In [ ]:
df=pd.DataFrame({
    "fruit":fruits,
    "basket_id":np.arange(N),
    "count":rng.integers(3,15,size=N),
    "weight":rng.uniform(0,4,size=N)
}, columns=["basket_id","fruit","count","weight"])

In [ ]:
df

   basket_id   fruit  count    weight
0          0   apple     11  1.564438
1          1  orange      5  1.331256
2          2   apple     12  2.393235
3          3   apple      6  0.746937
4          4   apple      5  2.691024
5          5  orange     12  3.767211
6          6   apple     10  0.992983
7          7   apple     11  3.795525

In [ ]:
fruit_cat=df["fruit"].astype("category")

In [ ]:
fruit_cat

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): ['apple', 'orange']

In [ ]:
c=fruit_cat.array

In [ ]:
type(c)

pandas.core.arrays.categorical.Categorical

In [ ]:
c.categories

Index(['apple', 'orange'], dtype='object')

In [ ]:
c.codes

array([0, 1, 0, 0, 0, 1, 0, 0], dtype=int8)

In [ ]:
dict(enumerate(c.categories))

TypeError: 'dict' object is not callable

In [ ]:
df["fruit"]=df["fruit"].astype("category")

In [ ]:
df["fruit"]

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): ['apple', 'orange']

In [ ]:
my_categories=pd.Categorical(["foo","bar","baz","foo","bar"])

In [ ]:
my_categories

['foo', 'bar', 'baz', 'foo', 'bar']
Categories (3, object): ['bar', 'baz', 'foo']

In [ ]:
categories=["foo","bar","baz"]

In [ ]:
codes=[0,1,2,0,0,1]

In [ ]:
my_cats_2=pd.Categorical.from_codes(codes,categories)

In [ ]:
my_cats_2

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo', 'bar', 'baz']

In [ ]:
ordered_cat=pd.Categorical.from_codes(codes,categories,ordered=True)

In [ ]:
ordered_cat

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo' < 'bar' < 'baz']

In [ ]:
my_cats_2

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo', 'bar', 'baz']

In [ ]:
my_cats_2.as_ordered()

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo' < 'bar' < 'baz']

Computations with Categoricals

In [180]:
rng=np.random.default_rng(seed=12345)

In [181]:
draws=rng.standard_normal(1000)

In [182]:
draws[:5]

array([-1.42382504,  1.26372846, -0.87066174, -0.25917323, -0.07534331])

In [183]:
bins=pd.qcut(draws,4)

In [184]:
bins

[(-3.121, -0.675], (0.687, 3.211], (-3.121, -0.675], (-0.675, 0.0134], (-0.675, 0.0134], ..., (0.0134, 0.687], (0.0134, 0.687], (-0.675, 0.0134], (0.0134, 0.687], (-0.675, 0.0134]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.121, -0.675] < (-0.675, 0.0134] < (0.0134, 0.687] < (0.687, 3.211]]

In [172]:
bins=pd.qcut(draws,4,labels=["Q1","Q2","Q3","Q4"])

In [173]:
bins

['Q1', 'Q4', 'Q1', 'Q2', 'Q2', ..., 'Q3', 'Q3', 'Q2', 'Q3', 'Q2']
Length: 1000
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [174]:
bins.codes[:10]

array([0, 3, 0, 1, 1, 0, 0, 2, 2, 0], dtype=int8)

In [175]:
bins=pd.Series(bins,name="quartile")

In [178]:
results=(pd.Series(draws).groupby(bins).agg(["count","min","max"]).reset_index())

C:\Users\Prathamesh Gawas\AppData\Local\Temp\ipykernel_24312\2602312380.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  results=(pd.Series(draws).groupby(bins).agg(["count","min","max"]).reset_index())

In [179]:
results

  quartile  count       min       max
0       Q1    250 -3.119609 -0.678494
1       Q2    250 -0.673305  0.008009
2       Q3    250  0.018753  0.686183
3       Q4    250  0.688282  3.211418

In [185]:
results["quartile"]

0    Q1
1    Q2
2    Q3
3    Q4
Name: quartile, dtype: category
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

Better performance with categoricals

In [191]:
N=10_000_000

In [192]:
labels=pd.Series(["foo","bar","baz","qux"]*(N//4))

In [193]:
categories=labels.astype("category")

In [194]:
labels.memory_usage(deep=True)

520000132

In [195]:
categories.memory_usage(deep=True)

10000512

In [196]:
%time _ =labels.astype("category")

CPU times: total: 625 ms
Wall time: 670 ms

In [197]:
%timeit labels.value_counts()

512 ms ± 49.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [198]:
%timeit categories.value_counts()

66 ms ± 6.58 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

Categorical Methods

In [199]:
s=pd.Series(["a","b","c","d"]*2)

In [200]:
cat_s=s.astype("category")

In [201]:
cat_s

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [203]:
cat_s.cat.codes

0    0
1    1
2    2
3    3
4    0
5    1
6    2
7    3
dtype: int8

In [204]:
actual_categories=["a","b","c","d","e"]

In [205]:
cat_s2=cat_s.cat.set_categories(actual_categories)

In [206]:
cat_s2

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (5, object): ['a', 'b', 'c', 'd', 'e']

In [207]:
cat_s.value_counts()

a    2
b    2
c    2
d    2
Name: count, dtype: int64

In [208]:
cat_s2.value_counts()

a    2
b    2
c    2
d    2
e    0
Name: count, dtype: int64

In [209]:
cat_s3=cat_s[cat_s.isin(["a","b"])]

In [211]:
cat_s3

0    a
1    b
4    a
5    b
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [212]:
cat_s3.cat.remove_unused_categories()

0    a
1    b
4    a
5    b
dtype: category
Categories (2, object): ['a', 'b']

## Table 7-7. Categorical methods for Series in pandas

| Method                | Description                                                                 | Example (Python) | Output |
|-----------------------|-----------------------------------------------------------------------------|------------------|--------|
| `add_categories`      | Append new (unused) categories at end of existing categories                | `s.cat.add_categories(["new"])` | Adds `"new"` as a category |
| `as_ordered`          | Make categories ordered                                                     | `s.cat.as_ordered()` | Categories become ordered |
| `as_unordered`        | Make categories unordered                                                   | `s.cat.as_unordered()` | Categories become unordered |
| `remove_categories`   | Remove categories, setting any removed values to null                       | `s.cat.remove_categories(["b"])` | `"b"` values → `NaN` |
| `remove_unused_categories` | Remove any category values that do not appear in the data              | `s.cat.remove_unused_categories()` | Drops unused categories |
| `rename_categories`   | Replace categories with new names; cannot change number of categories       | `s.cat.rename_categories({"a":"alpha","b":"beta"})` | Categories renamed |
| `reorder_categories`  | Behaves like `rename_categories`, but can also reorder categories           | `s.cat.reorder_categories(["b","a","c"])` | Categories reordered |
| `set_categories`      | Replace categories with new set; can add or remove categories               | `s.cat.set_categories(["x","y"])` | Categories replaced |

In [213]:
cat_s=pd.Series(["a","b","c","data"]*2,dtype="category")

In [216]:
cat_s

0       a
1       b
2       c
3    data
4       a
5       b
6       c
7    data
dtype: category
Categories (4, object): ['a', 'b', 'c', 'data']

In [215]:
pd.get_dummies(cat_s)

       a      b      c   data
0   True  False  False  False
1  False   True  False  False
2  False  False   True  False
3  False  False  False   True
4   True  False  False  False
5  False   True  False  False
6  False  False   True  False
7  False  False  False   True