# 8.1 Hierarchical Indexing

In [1]:
import numpy as np
import pandas as pd

In [2]:
data=pd.Series(np.random.uniform(size=9),
               index=[['a','a','a','b','b','c','c','d','d'],
                      [1,2,3,1,3,1,2,2,3]])

In [3]:
data

a  1    0.860216
   2    0.190138
   3    0.810183
b  1    0.297489
   3    0.727606
c  1    0.470692
   2    0.410070
d  2    0.424357
   3    0.926343
dtype: float64

In [4]:
data.index

MultiIndex([('a', 1),
            ('a', 2),
            ('a', 3),
            ('b', 1),
            ('b', 3),
            ('c', 1),
            ('c', 2),
            ('d', 2),
            ('d', 3)],
           )

In [5]:
data["b"]

1    0.297489
3    0.727606
dtype: float64

In [6]:
data["b":"c"]

b  1    0.297489
   3    0.727606
c  1    0.470692
   2    0.410070
dtype: float64

In [7]:
data.loc[["b","d"]]

b  1    0.297489
   3    0.727606
d  2    0.424357
   3    0.926343
dtype: float64

In [8]:
data.loc[:,2]

a    0.190138
c    0.410070
d    0.424357
dtype: float64

In [9]:
pd.DataFrame(data)

            0
a 1  0.860216
  2  0.190138
  3  0.810183
b 1  0.297489
  3  0.727606
c 1  0.470692
  2  0.410070
d 2  0.424357
  3  0.926343

In [10]:
data.unstack()

          1         2         3
a  0.860216  0.190138  0.810183
b  0.297489       NaN  0.727606
c  0.470692  0.410070       NaN
d       NaN  0.424357  0.926343

In [11]:
data.unstack().stack()

a  1    0.860216
   2    0.190138
   3    0.810183
b  1    0.297489
   3    0.727606
c  1    0.470692
   2    0.410070
d  2    0.424357
   3    0.926343
dtype: float64

In [12]:
frame=pd.DataFrame(np.arange(12).reshape((4,3)),
                   index=[["a","a","b","b"],
                          [1,2,1,2]],
                   columns=[["Ohio","Ohio","Colorado"],
                            ["Green","Red","Green"]])

In [13]:
frame

     Ohio     Colorado
    Green Red    Green
a 1     0   1        2
  2     3   4        5
b 1     6   7        8
  2     9  10       11

In [14]:
frame.index.names=["key1","key2"]

In [15]:
frame.columns.names=["state","color"]

In [16]:
frame

state      Ohio     Colorado
color     Green Red    Green
key1 key2
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

In [17]:
frame.index.nlevels

2

In [18]:
frame["Ohio"]

color      Green  Red
key1 key2
a    1         0    1
     2         3    4
b    1         6    7
     2         9   10

In [19]:
pd.MultiIndex.from_arrays(
    [["Ohio","Ohio","Colorado"],
     ["Green","Red","Green"]],
    names=["state","color"]
)

MultiIndex([(    'Ohio', 'Green'),
            (    'Ohio',   'Red'),
            ('Colorado', 'Green')],
           names=['state', 'color'])

Reordering and Sorting Levels

In [20]:
frame.swaplevel("key1","key2")

state      Ohio     Colorado
color     Green Red    Green
key2 key1
1    a        0   1        2
2    a        3   4        5
1    b        6   7        8
2    b        9  10       11

In [21]:
frame.sort_index(level=1)

state      Ohio     Colorado
color     Green Red    Green
key1 key2
a    1        0   1        2
b    1        6   7        8
a    2        3   4        5
b    2        9  10       11

In [22]:
frame.swaplevel(0,1).sort_index(level=0)

state      Ohio     Colorado
color     Green Red    Green
key2 key1
1    a        0   1        2
     b        6   7        8
2    a        3   4        5
     b        9  10       11

Summary Statistics by Level

In [23]:
frame.groupby(level="key2").sum()

state  Ohio     Colorado
color Green Red    Green
key2
1         6   8       10
2        12  14       16

In [24]:
frame

state      Ohio     Colorado
color     Green Red    Green
key1 key2
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

In [25]:
frame.groupby(level="color",axis="columns").sum()

C:\Users\Prathamesh Gawas\AppData\Local\Temp\ipykernel_37684\3295922660.py:1: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  frame.groupby(level="color",axis="columns").sum()

color      Green  Red
key1 key2
a    1         2    1
     2         8    4
b    1        14    7
     2        20   10

Indexing with a DataFrame’s columns

In [26]:
frame = pd.DataFrame({"a": range(7), "b": range(7, 0, -1),
                         "c": ["one", "one", "one", "two", "two",
                           "two", "two"],
                      "d": [0, 1, 2, 0, 1, 2, 3]})

In [27]:
frame

   a  b    c  d
0  0  7  one  0
1  1  6  one  1
2  2  5  one  2
3  3  4  two  0
4  4  3  two  1
5  5  2  two  2
6  6  1  two  3

In [28]:
frame2=frame.set_index(["c","d"])

In [29]:
frame2

       a  b
c   d
one 0  0  7
    1  1  6
    2  2  5
two 0  3  4
    1  4  3
    2  5  2
    3  6  1

In [30]:
frame.set_index(["c","d"],drop=False)

       a  b    c  d
c   d
one 0  0  7  one  0
    1  1  6  one  1
    2  2  5  one  2
two 0  3  4  two  0
    1  4  3  two  1
    2  5  2  two  2
    3  6  1  two  3

In [31]:
frame2.reset_index()

     c  d  a  b
0  one  0  0  7
1  one  1  1  6
2  one  2  2  5
3  two  0  3  4
4  two  1  4  3
5  two  2  5  2
6  two  3  6  1

# 8.2 Combining and Merging Datasets

In [32]:
df1 = pd.DataFrame({"key": ["b", "b", "a", "c", "a", "a", "b"],               
"data1": pd.Series(range(7), dtype="Int64")})

In [33]:
df2 = pd.DataFrame({"key": ["a", "b", "d"],                   
"data2": pd.Series(range(3), dtype="Int64")})

In [34]:
df1

  key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   a      5
6   b      6

In [35]:
df2

  key  data2
0   a      0
1   b      1
2   d      2

In [36]:
print(df1)
print(df2)

  key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   a      5
6   b      6
  key  data2
0   a      0
1   b      1
2   d      2

In [37]:
pd.merge(df1,df2)

  key  data1  data2
0   b      0      1
1   b      1      1
2   a      2      0
3   a      4      0
4   a      5      0
5   b      6      1

In [38]:
pd.merge(df1,df2,on="key")

  key  data1  data2
0   b      0      1
1   b      1      1
2   a      2      0
3   a      4      0
4   a      5      0
5   b      6      1

In [39]:
df3 = pd.DataFrame({"lkey": ["b", "b", "a", "c", "a", "a", "b"],
                   "data1": pd.Series(range(7), dtype="Int64")})

In [40]:
df4 = pd.DataFrame({"rkey": ["a", "b", "d"],
                     "data2": pd.Series(range(3), dtype="Int64")})

In [41]:
df3

  lkey  data1
0    b      0
1    b      1
2    a      2
3    c      3
4    a      4
5    a      5
6    b      6

In [42]:
df4

  rkey  data2
0    a      0
1    b      1
2    d      2

In [43]:
print(df3)
print(df4)

  lkey  data1
0    b      0
1    b      1
2    a      2
3    c      3
4    a      4
5    a      5
6    b      6
  rkey  data2
0    a      0
1    b      1
2    d      2

In [44]:
pd.merge(df3,df4,left_on="lkey",right_on="rkey")

  lkey  data1 rkey  data2
0    b      0    b      1
1    b      1    b      1
2    a      2    a      0
3    a      4    a      0
4    a      5    a      0
5    b      6    b      1

In [45]:
print(df1)
print(df2)

  key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   a      5
6   b      6
  key  data2
0   a      0
1   b      1
2   d      2

In [46]:
pd.merge(df1,df2,how="outer")

  key  data1  data2
0   a      2      0
1   a      4      0
2   a      5      0
3   b      0      1
4   b      1      1
5   b      6      1
6   c      3   <NA>
7   d   <NA>      2

In [47]:
pd.merge(df3,df4,left_on="lkey",right_on="rkey",how="outer")

  lkey  data1 rkey  data2
0    a      2    a      0
1    a      4    a      0
2    a      5    a      0
3    b      0    b      1
4    b      1    b      1
5    b      6    b      1
6    c      3  NaN   <NA>
7  NaN   <NA>    d      2

## Table 8-1. Different join types with the `how` argument

| Option        | Behavior                                                        | Example (Python) | Result |
|---------------|-----------------------------------------------------------------|------------------|--------|
| `how="inner"` | Use only the key combinations observed in both tables           | `pd.merge(df1, df2, how="inner", on="key")` | Intersection of keys |
| `how="left"`  | Use all key combinations found in the left table                 | `pd.merge(df1, df2, how="left", on="key")`  | All keys from left, match from right |
| `how="right"` | Use all key combinations found in the right table                | `pd.merge(df1, df2, how="right", on="key")` | All keys from right, match from left |
| `how="outer"` | Use all key combinations observed in both tables together        | `pd.merge(df1, df2, how="outer", on="key")` | Union of keys |

In [48]:
df1=pd.DataFrame({
    "key":list("bbacab"),
    "data1":pd.Series(range(6),dtype="Int64")
})

In [49]:
df2=pd.DataFrame({
    "key":list("ababd"),
    "data2":pd.Series(range(5),dtype="Int64")
})

In [50]:
df1

  key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [51]:
df2

  key  data2
0   a      0
1   b      1
2   a      2
3   b      3
4   d      4

In [52]:
pd.merge(df1,df2,on="key",how="left")

   key  data1  data2
0    b      0      1
1    b      0      3
2    b      1      1
3    b      1      3
4    a      2      0
5    a      2      2
6    c      3   <NA>
7    a      4      0
8    a      4      2
9    b      5      1
10   b      5      3

In [53]:
pd.merge(df1,df2,how="inner")

  key  data1  data2
0   b      0      1
1   b      0      3
2   b      1      1
3   b      1      3
4   a      2      0
5   a      2      2
6   a      4      0
7   a      4      2
8   b      5      1
9   b      5      3

In [54]:
left = pd.DataFrame({"key1": ["foo", "foo", "bar"],
                    
"key2": ["one", "two", "one"],
"lval": pd.Series([1, 2, 3], dtype='Int64')})

In [55]:
right=pd.DataFrame({"key1": ["foo", "foo", "bar", "bar"],
                    "key2": ["one", "one", "one", "two"],
                   "rval": pd.Series([4, 5, 6, 7], dtype='Int64')})

In [56]:
left

  key1 key2  lval
0  foo  one     1
1  foo  two     2
2  bar  one     3

In [57]:
right

  key1 key2  rval
0  foo  one     4
1  foo  one     5
2  bar  one     6
3  bar  two     7

In [58]:
pd.merge(left,right,on=["key1","key2"],how="outer")

  key1 key2  lval  rval
0  bar  one     3     6
1  bar  two  <NA>     7
2  foo  one     1     4
3  foo  one     1     5
4  foo  two     2  <NA>

In [59]:
left

  key1 key2  lval
0  foo  one     1
1  foo  two     2
2  bar  one     3

In [60]:
right

  key1 key2  rval
0  foo  one     4
1  foo  one     5
2  bar  one     6
3  bar  two     7

In [61]:
pd.merge(left,right,on="key1")

  key1 key2_x  lval key2_y  rval
0  foo    one     1    one     4
1  foo    one     1    one     5
2  foo    two     2    one     4
3  foo    two     2    one     5
4  bar    one     3    one     6
5  bar    one     3    two     7

In [62]:
pd.merge(left,right,on="key1",suffixes=("_left","_right"))

  key1 key2_left  lval key2_right  rval
0  foo       one     1        one     4
1  foo       one     1        one     5
2  foo       two     2        one     4
3  foo       two     2        one     5
4  bar       one     3        one     6
5  bar       one     3        two     7

## Arguments for `pandas.merge`

| Argument      | Description                                                                 | Example (Python) |
|---------------|-----------------------------------------------------------------------------|------------------|
| `left`        | DataFrame to be merged on the left side                                     | `pd.merge(df1, df2, ...)` |
| `right`       | DataFrame to be merged on the right side                                    | `pd.merge(df1, df2, ...)` |
| `how`         | Type of join: `"inner"`, `"outer"`, `"left"`, `"right"`; defaults to `"inner"` | `pd.merge(df1, df2, how="outer")` |
| `on`          | Column names to join on; must exist in both DataFrames. If not specified, uses intersection of column names | `pd.merge(df1, df2, on="id")` |
| `left_on`     | Column(s) in left DataFrame to use as join keys                             | `pd.merge(df1, df2, left_on="id1", right_on="id2")` |
| `right_on`    | Column(s) in right DataFrame to use as join keys                            | Same as above |
| `left_index`  | Use row index in left as join key (supports MultiIndex)                     | `pd.merge(df1, df2, left_index=True, right_on="id")` |
| `right_index` | Use row index in right as join key                                          | `pd.merge(df1, df2, right_index=True, left_on="id")` |
| `sort`        | Sort merged data lexicographically by join keys; default `False`            | `pd.merge(df1, df2, on="id", sort=True)` |
| `suffixes`    | Tuple of suffixes for overlapping column names; default `("_x","_y")`       | `pd.merge(df1, df2, on="id", suffixes=("_left","_right"))` |
| `copy`        | If `False`, avoid copying data in some cases; default always copies         | `pd.merge(df1, df2, copy=False)` |
| `validate`    | Verifies merge type: `"1:1"`, `"1:m"`, `"m:1"`, `"m:m"`                     | `pd.merge(df1, df2, on="id", validate="1:1")` |
| `indicator`   | Adds `_merge` column showing source of each row: `"left_only"`, `"right_only"`, `"both"` | `pd.merge(df1, df2, on="id", indicator=True)` |

Merging on Index

In [63]:
left1=pd.DataFrame({
    "key":list("abaabc"),
    "value":pd.Series(range(6),dtype="Int64")
})

In [64]:
right1=pd.DataFrame({
    "group_val":[3.5,7]
},
                    index=["a","b"])

In [65]:
left1

  key  value
0   a      0
1   b      1
2   a      2
3   a      3
4   b      4
5   c      5

In [66]:
right1

   group_val
a        3.5
b        7.0

In [67]:
pd.merge(left1,right1,left_on="key",right_index=True)

  key  value  group_val
0   a      0        3.5
1   b      1        7.0
2   a      2        3.5
3   a      3        3.5
4   b      4        7.0

In [68]:
pd.merge(left1,right1,left_on="key",right_index=True,how="outer")

  key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0
5   c      5        NaN

In [69]:
lefth=pd.DataFrame({
    "key1":["Ohio","Ohio","Ohio","Nevada","Nevada"],
    "key2":[2000,2001,2002,2001,2002],
    "data1":pd.Series(np.arange(5),dtype="Int64")
})

In [70]:
righth_index = pd.MultiIndex.from_arrays(
   [["Nevada", "Nevada", "Ohio", "Ohio", "Ohio", "Ohio"],[2001, 2000, 2000, 2000, 2001, 2002]]
    )

In [71]:
righth=pd.DataFrame({
    "event1":pd.Series([0,2,4,6,8,10],dtype="Int64",index=righth_index),
    "event2":pd.Series([1,3,5,7,9,11],dtype="Int64",index=righth_index)
})

In [72]:
lefth

     key1  key2  data1
0    Ohio  2000      0
1    Ohio  2001      1
2    Ohio  2002      2
3  Nevada  2001      3
4  Nevada  2002      4

In [73]:
righth_index

MultiIndex([('Nevada', 2001),
            ('Nevada', 2000),
            (  'Ohio', 2000),
            (  'Ohio', 2000),
            (  'Ohio', 2001),
            (  'Ohio', 2002)],
           )

In [74]:
righth

             event1  event2
Nevada 2001       0       1
       2000       2       3
Ohio   2000       4       5
       2000       6       7
       2001       8       9
       2002      10      11

In [75]:
pd.merge(lefth,righth,left_on=["key1","key2"],right_index=True)

     key1  key2  data1  event1  event2
0    Ohio  2000      0       4       5
0    Ohio  2000      0       6       7
1    Ohio  2001      1       8       9
2    Ohio  2002      2      10      11
3  Nevada  2001      3       0       1

In [76]:
pd.merge(lefth,righth,left_on=["key1","key2"],right_index=True,how="outer")

     key1  key2  data1  event1  event2
4  Nevada  2000   <NA>       2       3
3  Nevada  2001      3       0       1
4  Nevada  2002      4    <NA>    <NA>
0    Ohio  2000      0       4       5
0    Ohio  2000      0       6       7
1    Ohio  2001      1       8       9
2    Ohio  2002      2      10      11

In [77]:
left2=pd.DataFrame([[1.,2.],[3.,4.],[5.,6.]],
                   index=["a","c","e"],
                   columns=["Ohio","Nevada"]).astype("Int64")

In [78]:
right2=pd.DataFrame([[7.,8.],[9.,10.],[11.,12.],[13.,14.]],
                   index=["a","c","e","f"],
                   columns=["Missouri","Alabama"]).astype("Int64")

In [79]:
left2

   Ohio  Nevada
a     1       2
c     3       4
e     5       6

In [80]:
right2

   Missouri  Alabama
a         7        8
c         9       10
e        11       12
f        13       14

In [81]:
pd.merge(left2,right2,how="outer",left_index=True,right_index=True)

   Ohio  Nevada  Missouri  Alabama
a     1       2         7        8
c     3       4         9       10
e     5       6        11       12
f  <NA>    <NA>        13       14

In [82]:
left2.join(right2,how="outer")

   Ohio  Nevada  Missouri  Alabama
a     1       2         7        8
c     3       4         9       10
e     5       6        11       12
f  <NA>    <NA>        13       14

In [83]:
left1.join(right1,on="key")

  key  value  group_val
0   a      0        3.5
1   b      1        7.0
2   a      2        3.5
3   a      3        3.5
4   b      4        7.0
5   c      5        NaN

In [84]:
another = pd.DataFrame([[7., 8.], [9., 10.], [11., 12.], [16., 17.]],                   
                       index=["a", "c", "e", "f"],
                      columns=["New York", "Oregon"])

In [85]:
another

   New York  Oregon
a       7.0     8.0
c       9.0    10.0
e      11.0    12.0
f      16.0    17.0

In [86]:
left2.join([right2,another])

   Ohio  Nevada  Missouri  Alabama  New York  Oregon
a     1       2         7        8       7.0     8.0
c     3       4         9       10       9.0    10.0
e     5       6        11       12      11.0    12.0

In [87]:
left2.join([right2,another],how="outer")

   Ohio  Nevada  Missouri  Alabama  New York  Oregon
a     1       2         7        8       7.0     8.0
c     3       4         9       10       9.0    10.0
e     5       6        11       12      11.0    12.0
f  <NA>    <NA>        13       14      16.0    17.0

Concatenating Along an Axis

In [88]:
arr=np.arange(12).reshape((3,4))

In [89]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [90]:
np.concatenate([arr,arr],axis=1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [91]:
s1=pd.Series([0,1],index=["a","b"],dtype="Int64")

In [92]:
s2=pd.Series([2,3,4],index=["c","d","e"],dtype="Int64")

In [93]:
s3=pd.Series([5,6],index=["f","g"],dtype="Int64")

In [94]:
s1

a    0
b    1
dtype: Int64

In [95]:
s2

c    2
d    3
e    4
dtype: Int64

In [96]:
s3

f    5
g    6
dtype: Int64

In [97]:
pd.concat([s1,s2,s3])

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: Int64

In [98]:
pd.concat([s1,s2,s3],axis="columns")

      0     1     2
a     0  <NA>  <NA>
b     1  <NA>  <NA>
c  <NA>     2  <NA>
d  <NA>     3  <NA>
e  <NA>     4  <NA>
f  <NA>  <NA>     5
g  <NA>  <NA>     6

In [99]:
s4=pd.concat([s1,s3])

In [100]:
s4

a    0
b    1
f    5
g    6
dtype: Int64

In [101]:
pd.concat([s1,s4],axis="columns")

      0  1
a     0  0
b     1  1
f  <NA>  5
g  <NA>  6

In [102]:
s1

a    0
b    1
dtype: Int64

In [103]:
s4

a    0
b    1
f    5
g    6
dtype: Int64

In [104]:
pd.concat([s1,s4],axis="columns",join="inner")

   0  1
a  0  0
b  1  1

In [105]:
result=pd.concat([s1,s1,s3],keys=["one","two","three"])

In [106]:
result

one    a    0
       b    1
two    a    0
       b    1
three  f    5
       g    6
dtype: Int64

In [107]:
result.unstack()

          a     b     f     g
one       0     1  <NA>  <NA>
two       0     1  <NA>  <NA>
three  <NA>  <NA>     5     6

In [108]:
pd.concat([s1,s2,s3],axis="columns",keys=["one","two","three"])

    one   two  three
a     0  <NA>   <NA>
b     1  <NA>   <NA>
c  <NA>     2   <NA>
d  <NA>     3   <NA>
e  <NA>     4   <NA>
f  <NA>  <NA>      5
g  <NA>  <NA>      6

In [109]:
df1=pd.DataFrame(
    np.arange(6).reshape(3,2),
    index=["a","b","c"],
    columns=["one","two"]
)

In [110]:
df2=pd.DataFrame(
    5+np.arange(4).reshape(2,2),
    index=["a","c"],
    columns=["three","four"]
)

In [111]:
df1

   one  two
a    0    1
b    2    3
c    4    5

In [112]:
df2

   three  four
a      5     6
c      7     8

In [113]:
pd.concat([df1,df2],axis="columns",keys=["level1","level2"])

  level1     level2
     one two  three four
a      0   1    5.0  6.0
b      2   3    NaN  NaN
c      4   5    7.0  8.0

In [114]:
pd.concat({
    "level1":df1,
    "level2":df2
},
          axis="columns")

  level1     level2
     one two  three four
a      0   1    5.0  6.0
b      2   3    NaN  NaN
c      4   5    7.0  8.0

In [115]:
pd.concat([df1,df2],axis="columns",keys=["level1","level2"],names=["upper","lower"])

upper level1     level2
lower    one two  three four
a          0   1    5.0  6.0
b          2   3    NaN  NaN
c          4   5    7.0  8.0

In [116]:
df1=pd.DataFrame(np.random.standard_normal((3,4)),
                 columns=list("abcd"))

In [117]:
df2=pd.DataFrame(np.random.standard_normal((2,3)),
                 columns=list("bda"))

In [118]:
df1

          a         b         c         d
0  0.244008  0.572661 -0.084909 -0.745649
1 -0.256753 -1.066532 -0.543128 -0.290015
2  1.231050  0.330818  0.269740  0.405593

In [119]:
df2

          b         d         a
0  0.092576 -0.389301 -0.271980
1 -2.372637  0.071349  1.063396

In [120]:
pd.concat([df1,df2],ignore_index=True)

          a         b         c         d
0  0.244008  0.572661 -0.084909 -0.745649
1 -0.256753 -1.066532 -0.543128 -0.290015
2  1.231050  0.330818  0.269740  0.405593
3 -0.271980  0.092576       NaN -0.389301
4  1.063396 -2.372637       NaN  0.071349

## Arguments for `pandas.concat`

| Argument          | Description                                                                 | Example (Python) |
|-------------------|-----------------------------------------------------------------------------|------------------|
| `objs`            | List or dictionary of pandas objects to be concatenated; required argument  | `pd.concat([df1, df2])` |
| `axis`            | Axis to concatenate along; default is rows (`axis=0` or `"index"`)          | `pd.concat([df1, df2], axis=1)` |
| `join`            | `"inner"` or `"outer"` (`"outer"` by default); controls intersection vs union of indexes | `pd.concat([df1, df2], join="inner")` |
| `keys`            | Values to associate with objects being concatenated, forming hierarchical index | `pd.concat([df1, df2], keys=["A","B"])` |
| `levels`          | Specific indexes to use as hierarchical index levels if `keys` passed       | `pd.concat([df1, df2], keys=["A","B"], levels=[["A","B"]])` |
| `names`           | Names for created hierarchical levels if `keys`/`levels` passed             | `pd.concat([df1, df2], keys=["A","B"], names=["source"])` |
| `ignore_index`    | Do not preserve indexes; produce new range index                            | `pd.concat([df1, df2], ignore_index=True)` |
| `verify_integrity`| Check new axis for duplicates and raise exception if found; default `False` | `pd.concat([df1, df2], verify_integrity=True)` |

Combining Data with Overlap

In [121]:
a=pd.Series([np.nan,2.5,0.0,3.5,4.5,np.nan],
            index=list("fedcba"))

In [122]:
b=pd.Series([0., np.nan, 2., np.nan, np.nan, 5.],
            index=list("abcdef"))

In [123]:
a

f    NaN
e    2.5
d    0.0
c    3.5
b    4.5
a    NaN
dtype: float64

In [124]:
b

a    0.0
b    NaN
c    2.0
d    NaN
e    NaN
f    5.0
dtype: float64

In [125]:
np.where(pd.isna(a),b,a)

array([0. , 2.5, 0. , 3.5, 4.5, 5. ])

In [126]:
a.combine_first(b)

a    0.0
b    4.5
c    3.5
d    0.0
e    2.5
f    5.0
dtype: float64

In [127]:
df1=pd.DataFrame({
"a": [1., np.nan, 5., np.nan],                    
"b": [np.nan, 2., np.nan, 6.],
"c": range(2, 18, 4)  
})

In [128]:
df2 = pd.DataFrame({"a": [5., 4., np.nan, 3., 7.],
                    "b": [np.nan, 3., 4., 6., 8.]})

In [129]:
df1

     a    b   c
0  1.0  NaN   2
1  NaN  2.0   6
2  5.0  NaN  10
3  NaN  6.0  14

In [130]:
df2

     a    b
0  5.0  NaN
1  4.0  3.0
2  NaN  4.0
3  3.0  6.0
4  7.0  8.0

In [131]:
df1.combine_first(df2)

     a    b     c
0  1.0  NaN   2.0
1  4.0  2.0   6.0
2  5.0  4.0  10.0
3  3.0  6.0  14.0
4  7.0  8.0   NaN

# 8.3 Reshaping and Pivoting

Reshaping with Hierarchical Indexing

In [133]:
data=pd.DataFrame(np.arange(6).reshape((2,3)),
                  index=pd.Index(["Ohio","Colorado"],
                    name="state"),columns=pd.Index(["one","two","three"],
                    name="number"))

In [134]:
data

number    one  two  three
state
Ohio        0    1      2
Colorado    3    4      5

In [135]:
result=data.stack()

In [136]:
result

state     number
Ohio      one       0
          two       1
          three     2
Colorado  one       3
          two       4
          three     5
dtype: int64

In [137]:
result.unstack()

number    one  two  three
state
Ohio        0    1      2
Colorado    3    4      5

In [138]:
result.unstack(level="state")

state   Ohio  Colorado
number
one        0         3
two        1         4
three      2         5

In [148]:
s1=pd.Series([0,1,2,3],index=["a","b","c","d"],dtype="Int64")

In [149]:
s2=pd.Series([4,5,6],index=["c","d","e"],dtype="Int64")

In [150]:
data2=pd.concat([s1,s2],keys=["one","two"])

In [151]:
data2

one  a    0
     b    1
     c    2
     d    3
two  c    4
     d    5
     e    6
dtype: Int64

In [152]:
data2.unstack()

        a     b  c  d     e
one     0     1  2  3  <NA>
two  <NA>  <NA>  4  5     6

In [153]:
data2.unstack().stack()

one  a    0
     b    1
     c    2
     d    3
two  c    4
     d    5
     e    6
dtype: Int64

In [156]:
data2.unstack().stack(future_stack=True) # instead of dropna used future_stack because dropna is deprecated in newer pandas version

one  a       0
     b       1
     c       2
     d       3
     e    <NA>
two  a    <NA>
     b    <NA>
     c       4
     d       5
     e       6
dtype: Int64

In [157]:
df=pd.DataFrame({
    "left":result,
    "right":result+5
},
columns=pd.Index(["left","right"],name="side"))

In [158]:
df

side             left  right
state    number
Ohio     one        0      5
         two        1      6
         three      2      7
Colorado one        3      8
         two        4      9
         three      5     10

In [159]:
df.unstack(level="state")

side   left          right
state  Ohio Colorado  Ohio Colorado
number
one       0        3     5        8
two       1        4     6        9
three     2        5     7       10

In [160]:
df.unstack(level="state").stack(level="side")

C:\Users\Prathamesh Gawas\AppData\Local\Temp\ipykernel_37684\2617337668.py:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  df.unstack(level="state").stack(level="side")

state         Ohio  Colorado
number side
one    left      0         3
       right     5         8
two    left      1         4
       right     6         9
three  left      2         5
       right     7        10

In [161]:
data=pd.read_csv("examples/macrodata.csv")

In [163]:
data=data.loc[:,["year","quarter","realgdp","infl","unemp"]]

In [164]:
data.head()

   year  quarter   realgdp  infl  unemp
0  1959        1  2710.349  0.00    5.8
1  1959        2  2778.801  2.34    5.1
2  1959        3  2775.488  2.74    5.3
3  1959        4  2785.204  0.27    5.6
4  1960        1  2847.699  2.31    5.2

In [165]:
periods=pd.PeriodIndex(year=data.pop("year"),
                       quarter=data.pop("quarter"),
                       name="date")

C:\Users\Prathamesh Gawas\AppData\Local\Temp\ipykernel_37684\1688047542.py:1: FutureWarning: Constructing PeriodIndex from fields is deprecated. Use PeriodIndex.from_fields instead.
  periods=pd.PeriodIndex(year=data.pop("year"),

In [174]:
periods

PeriodIndex(['1959Q1', '1959Q2', '1959Q3', '1959Q4', '1960Q1', '1960Q2',
             '1960Q3', '1960Q4', '1961Q1', '1961Q2',
             ...
             '2007Q2', '2007Q3', '2007Q4', '2008Q1', '2008Q2', '2008Q3',
             '2008Q4', '2009Q1', '2009Q2', '2009Q3'],
            dtype='period[Q-DEC]', name='date', length=203)

In [167]:
data.index=periods.to_timestamp("D")

In [168]:
data.head()

             realgdp  infl  unemp
date
1959-01-01  2710.349  0.00    5.8
1959-04-01  2778.801  2.34    5.1
1959-07-01  2775.488  2.74    5.3
1959-10-01  2785.204  0.27    5.6
1960-01-01  2847.699  2.31    5.2

In [169]:
data=data.reindex(columns=["realgdp","infl","unrmp"])

In [170]:
data.columns.name="item"

In [171]:
data.head()

item         realgdp  infl  unrmp
date
1959-01-01  2710.349  0.00    NaN
1959-04-01  2778.801  2.34    NaN
1959-07-01  2775.488  2.74    NaN
1959-10-01  2785.204  0.27    NaN
1960-01-01  2847.699  2.31    NaN

In [175]:
long_data=(data.stack().reset_index().rename(columns={0:"value"}))

In [177]:
long_data[:10]

        date     item     value
0 1959-01-01  realgdp  2710.349
1 1959-01-01     infl     0.000
2 1959-04-01  realgdp  2778.801
3 1959-04-01     infl     2.340
4 1959-07-01  realgdp  2775.488
5 1959-07-01     infl     2.740
6 1959-10-01  realgdp  2785.204
7 1959-10-01     infl     0.270
8 1960-01-01  realgdp  2847.699
9 1960-01-01     infl     2.310

In [187]:
pivoted=long_data.pivot(index="date",columns="item",values="value")

In [188]:
pivoted.head()

item        infl   realgdp
date
1959-01-01  0.00  2710.349
1959-04-01  2.34  2778.801
1959-07-01  2.74  2775.488
1959-10-01  0.27  2785.204
1960-01-01  2.31  2847.699

In [182]:
long_data["value2"]=np.random.standard_normal(len(long_data))

In [183]:
long_data.head(10)

        date     item     value    value2
0 1959-01-01  realgdp  2710.349  0.875486
1 1959-01-01     infl     0.000 -0.232388
2 1959-04-01  realgdp  2778.801  0.168781
3 1959-04-01     infl     2.340 -0.473725
4 1959-07-01  realgdp  2775.488 -0.584108
5 1959-07-01     infl     2.740  0.067389
6 1959-10-01  realgdp  2785.204  1.801308
7 1959-10-01     infl     0.270 -1.649009
8 1960-01-01  realgdp  2847.699 -1.575035
9 1960-01-01     infl     2.310 -0.719208

In [184]:
pivoted=long_data.pivot(index="date",columns="item")

In [185]:
pivoted.head()

           value              value2
item        infl   realgdp      infl   realgdp
date
1959-01-01  0.00  2710.349 -0.232388  0.875486
1959-04-01  2.34  2778.801 -0.473725  0.168781
1959-07-01  2.74  2775.488  0.067389 -0.584108
1959-10-01  0.27  2785.204 -1.649009  1.801308
1960-01-01  2.31  2847.699 -0.719208 -1.575035

In [186]:
pivoted["value"].head()

item        infl   realgdp
date
1959-01-01  0.00  2710.349
1959-04-01  2.34  2778.801
1959-07-01  2.74  2775.488
1959-10-01  0.27  2785.204
1960-01-01  2.31  2847.699

In [189]:
unstacked=long_data.set_index(["date","item"]).unstack(level="item")

In [190]:
unstacked.head()

           value              value2
item        infl   realgdp      infl   realgdp
date
1959-01-01  0.00  2710.349 -0.232388  0.875486
1959-04-01  2.34  2778.801 -0.473725  0.168781
1959-07-01  2.74  2775.488  0.067389 -0.584108
1959-10-01  0.27  2785.204 -1.649009  1.801308
1960-01-01  2.31  2847.699 -0.719208 -1.575035

# Pivoting “Wide” to “Long” Format

In [191]:
df=pd.DataFrame({
    "key":["foo","bar","baz"],
    "A":list("123"),
    "B":list("456"),
    "C":list("789")
})

In [192]:
df

   key  A  B  C
0  foo  1  4  7
1  bar  2  5  8
2  baz  3  6  9

In [193]:
melted=pd.melt(df,id_vars="key")

In [194]:
melted

   key variable value
0  foo        A     1
1  bar        A     2
2  baz        A     3
3  foo        B     4
4  bar        B     5
5  baz        B     6
6  foo        C     7
7  bar        C     8
8  baz        C     9

In [195]:
reshaped=melted.pivot(index="key",columns="variable",values="value")

In [196]:
reshaped

variable  A  B  C
key
bar       2  5  8
baz       3  6  9
foo       1  4  7

In [197]:
reshaped.reset_index()

variable  key  A  B  C
0         bar  2  5  8
1         baz  3  6  9
2         foo  1  4  7

In [198]:
pd.melt(df,id_vars="key",value_vars=["A","B"])

   key variable value
0  foo        A     1
1  bar        A     2
2  baz        A     3
3  foo        B     4
4  bar        B     5
5  baz        B     6

In [199]:
pd.melt(df,value_vars=["A","B","C"])

  variable value
0        A     1
1        A     2
2        A     3
3        B     4
4        B     5
5        B     6
6        C     7
7        C     8
8        C     9

In [201]:
pd.melt(df, value_vars=["key", "A", "B"])

  variable value
0      key   foo
1      key   bar
2      key   baz
3        A     1
4        A     2
5        A     3
6        B     4
7        B     5
8        B     6