# 8.1 Hierarchical Indexing

In [2]:
import numpy as np
import pandas as pd

In [3]:
data=pd.Series(np.random.uniform(size=9),
               index=[['a','a','a','b','b','c','c','d','d'],
                      [1,2,3,1,3,1,2,2,3]])

In [4]:
data

a  1    0.714943
   2    0.736226
   3    0.761425
b  1    0.266297
   3    0.230684
c  1    0.842549
   2    0.501288
d  2    0.025514
   3    0.074184
dtype: float64

In [5]:
data.index

MultiIndex([('a', 1),
            ('a', 2),
            ('a', 3),
            ('b', 1),
            ('b', 3),
            ('c', 1),
            ('c', 2),
            ('d', 2),
            ('d', 3)],
           )

In [6]:
data["b"]

1    0.266297
3    0.230684
dtype: float64

In [7]:
data["b":"c"]

b  1    0.266297
   3    0.230684
c  1    0.842549
   2    0.501288
dtype: float64

In [8]:
data.loc[["b","d"]]

b  1    0.266297
   3    0.230684
d  2    0.025514
   3    0.074184
dtype: float64

In [9]:
data.loc[:,2]

a    0.736226
c    0.501288
d    0.025514
dtype: float64

In [10]:
pd.DataFrame(data)

            0
a 1  0.714943
  2  0.736226
  3  0.761425
b 1  0.266297
  3  0.230684
c 1  0.842549
  2  0.501288
d 2  0.025514
  3  0.074184

In [11]:
data.unstack()

          1         2         3
a  0.714943  0.736226  0.761425
b  0.266297       NaN  0.230684
c  0.842549  0.501288       NaN
d       NaN  0.025514  0.074184

In [12]:
data.unstack().stack()

a  1    0.714943
   2    0.736226
   3    0.761425
b  1    0.266297
   3    0.230684
c  1    0.842549
   2    0.501288
d  2    0.025514
   3    0.074184
dtype: float64

In [13]:
frame=pd.DataFrame(np.arange(12).reshape((4,3)),
                   index=[["a","a","b","b"],
                          [1,2,1,2]],
                   columns=[["Ohio","Ohio","Colorado"],
                            ["Green","Red","Green"]])

In [14]:
frame

     Ohio     Colorado
    Green Red    Green
a 1     0   1        2
  2     3   4        5
b 1     6   7        8
  2     9  10       11

In [15]:
frame.index.names=["key1","key2"]

In [16]:
frame.columns.names=["state","color"]

In [17]:
frame

state      Ohio     Colorado
color     Green Red    Green
key1 key2
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

In [18]:
frame.index.nlevels

2

In [19]:
frame["Ohio"]

color      Green  Red
key1 key2
a    1         0    1
     2         3    4
b    1         6    7
     2         9   10

In [20]:
pd.MultiIndex.from_arrays(
    [["Ohio","Ohio","Colorado"],
     ["Green","Red","Green"]],
    names=["state","color"]
)

MultiIndex([(    'Ohio', 'Green'),
            (    'Ohio',   'Red'),
            ('Colorado', 'Green')],
           names=['state', 'color'])

Reordering and Sorting Levels

In [21]:
frame.swaplevel("key1","key2")

state      Ohio     Colorado
color     Green Red    Green
key2 key1
1    a        0   1        2
2    a        3   4        5
1    b        6   7        8
2    b        9  10       11

In [22]:
frame.sort_index(level=1)

state      Ohio     Colorado
color     Green Red    Green
key1 key2
a    1        0   1        2
b    1        6   7        8
a    2        3   4        5
b    2        9  10       11

In [23]:
frame.swaplevel(0,1).sort_index(level=0)

state      Ohio     Colorado
color     Green Red    Green
key2 key1
1    a        0   1        2
     b        6   7        8
2    a        3   4        5
     b        9  10       11

Summary Statistics by Level

In [24]:
frame.groupby(level="key2").sum()

state  Ohio     Colorado
color Green Red    Green
key2
1         6   8       10
2        12  14       16

In [25]:
frame

state      Ohio     Colorado
color     Green Red    Green
key1 key2
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

In [26]:
frame.groupby(level="color",axis="columns").sum()

C:\Users\Prathamesh Gawas\AppData\Local\Temp\ipykernel_10020\3295922660.py:1: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  frame.groupby(level="color",axis="columns").sum()

color      Green  Red
key1 key2
a    1         2    1
     2         8    4
b    1        14    7
     2        20   10

Indexing with a DataFrame’s columns

In [27]:
frame = pd.DataFrame({"a": range(7), "b": range(7, 0, -1),
                         "c": ["one", "one", "one", "two", "two",
                           "two", "two"],
                      "d": [0, 1, 2, 0, 1, 2, 3]})

In [28]:
frame

   a  b    c  d
0  0  7  one  0
1  1  6  one  1
2  2  5  one  2
3  3  4  two  0
4  4  3  two  1
5  5  2  two  2
6  6  1  two  3

In [29]:
frame2=frame.set_index(["c","d"])

In [30]:
frame2

       a  b
c   d
one 0  0  7
    1  1  6
    2  2  5
two 0  3  4
    1  4  3
    2  5  2
    3  6  1

In [31]:
frame.set_index(["c","d"],drop=False)

       a  b    c  d
c   d
one 0  0  7  one  0
    1  1  6  one  1
    2  2  5  one  2
two 0  3  4  two  0
    1  4  3  two  1
    2  5  2  two  2
    3  6  1  two  3

In [32]:
frame2.reset_index()

     c  d  a  b
0  one  0  0  7
1  one  1  1  6
2  one  2  2  5
3  two  0  3  4
4  two  1  4  3
5  two  2  5  2
6  two  3  6  1

# 8.2 Combining and Merging Datasets

In [49]:
df1 = pd.DataFrame({"key": ["b", "b", "a", "c", "a", "a", "b"],               
"data1": pd.Series(range(7), dtype="Int64")})

In [50]:
df2 = pd.DataFrame({"key": ["a", "b", "d"],                   
"data2": pd.Series(range(3), dtype="Int64")})

In [51]:
df1

  key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   a      5
6   b      6

In [52]:
df2

  key  data2
0   a      0
1   b      1
2   d      2

In [53]:
print(df1)
print(df2)

  key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   a      5
6   b      6
  key  data2
0   a      0
1   b      1
2   d      2

In [54]:
pd.merge(df1,df2)

  key  data1  data2
0   b      0      1
1   b      1      1
2   a      2      0
3   a      4      0
4   a      5      0
5   b      6      1

In [55]:
pd.merge(df1,df2,on="key")

  key  data1  data2
0   b      0      1
1   b      1      1
2   a      2      0
3   a      4      0
4   a      5      0
5   b      6      1

In [57]:
df3 = pd.DataFrame({"lkey": ["b", "b", "a", "c", "a", "a", "b"],
                   "data1": pd.Series(range(7), dtype="Int64")})

In [58]:
df4 = pd.DataFrame({"rkey": ["a", "b", "d"],
                     "data2": pd.Series(range(3), dtype="Int64")})

In [59]:
df3

  lkey  data1
0    b      0
1    b      1
2    a      2
3    c      3
4    a      4
5    a      5
6    b      6

In [60]:
df4

  rkey  data2
0    a      0
1    b      1
2    d      2

In [62]:
print(df3)
print(df4)

  lkey  data1
0    b      0
1    b      1
2    a      2
3    c      3
4    a      4
5    a      5
6    b      6
  rkey  data2
0    a      0
1    b      1
2    d      2

In [61]:
pd.merge(df3,df4,left_on="lkey",right_on="rkey")

  lkey  data1 rkey  data2
0    b      0    b      1
1    b      1    b      1
2    a      2    a      0
3    a      4    a      0
4    a      5    a      0
5    b      6    b      1

In [64]:
print(df1)
print(df2)

  key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   a      5
6   b      6
  key  data2
0   a      0
1   b      1
2   d      2

In [65]:
pd.merge(df1,df2,how="outer")

  key  data1  data2
0   a      2      0
1   a      4      0
2   a      5      0
3   b      0      1
4   b      1      1
5   b      6      1
6   c      3   <NA>
7   d   <NA>      2

In [66]:
pd.merge(df3,df4,left_on="lkey",right_on="rkey",how="outer")

  lkey  data1 rkey  data2
0    a      2    a      0
1    a      4    a      0
2    a      5    a      0
3    b      0    b      1
4    b      1    b      1
5    b      6    b      1
6    c      3  NaN   <NA>
7  NaN   <NA>    d      2

## Table 8-1. Different join types with the `how` argument

| Option        | Behavior                                                        | Example (Python) | Result |
|---------------|-----------------------------------------------------------------|------------------|--------|
| `how="inner"` | Use only the key combinations observed in both tables           | `pd.merge(df1, df2, how="inner", on="key")` | Intersection of keys |
| `how="left"`  | Use all key combinations found in the left table                 | `pd.merge(df1, df2, how="left", on="key")`  | All keys from left, match from right |
| `how="right"` | Use all key combinations found in the right table                | `pd.merge(df1, df2, how="right", on="key")` | All keys from right, match from left |
| `how="outer"` | Use all key combinations observed in both tables together        | `pd.merge(df1, df2, how="outer", on="key")` | Union of keys |

In [67]:
df1=pd.DataFrame({
    "key":list("bbacab"),
    "data1":pd.Series(range(6),dtype="Int64")
})

In [68]:
df2=pd.DataFrame({
    "key":list("ababd"),
    "data2":pd.Series(range(5),dtype="Int64")
})

In [69]:
df1

  key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [70]:
df2

  key  data2
0   a      0
1   b      1
2   a      2
3   b      3
4   d      4

In [75]:
pd.merge(df1,df2,on="key",how="left")

   key  data1  data2
0    b      0      1
1    b      0      3
2    b      1      1
3    b      1      3
4    a      2      0
5    a      2      2
6    c      3   <NA>
7    a      4      0
8    a      4      2
9    b      5      1
10   b      5      3

In [76]:
pd.merge(df1,df2,how="inner")

  key  data1  data2
0   b      0      1
1   b      0      3
2   b      1      1
3   b      1      3
4   a      2      0
5   a      2      2
6   a      4      0
7   a      4      2
8   b      5      1
9   b      5      3

In [77]:
left = pd.DataFrame({"key1": ["foo", "foo", "bar"],
                    
"key2": ["one", "two", "one"],
"lval": pd.Series([1, 2, 3], dtype='Int64')})

In [78]:
right=pd.DataFrame({"key1": ["foo", "foo", "bar", "bar"],
                    "key2": ["one", "one", "one", "two"],
                   "rval": pd.Series([4, 5, 6, 7], dtype='Int64')})

In [79]:
left

  key1 key2  lval
0  foo  one     1
1  foo  two     2
2  bar  one     3

In [80]:
right

  key1 key2  rval
0  foo  one     4
1  foo  one     5
2  bar  one     6
3  bar  two     7

In [83]:
pd.merge(left,right,on=["key1","key2"],how="outer")

  key1 key2  lval  rval
0  bar  one     3     6
1  bar  two  <NA>     7
2  foo  one     1     4
3  foo  one     1     5
4  foo  two     2  <NA>

In [85]:
left

  key1 key2  lval
0  foo  one     1
1  foo  two     2
2  bar  one     3

In [86]:
right

  key1 key2  rval
0  foo  one     4
1  foo  one     5
2  bar  one     6
3  bar  two     7

In [84]:
pd.merge(left,right,on="key1")

  key1 key2_x  lval key2_y  rval
0  foo    one     1    one     4
1  foo    one     1    one     5
2  foo    two     2    one     4
3  foo    two     2    one     5
4  bar    one     3    one     6
5  bar    one     3    two     7

In [87]:
pd.merge(left,right,on="key1",suffixes=("_left","_right"))

  key1 key2_left  lval key2_right  rval
0  foo       one     1        one     4
1  foo       one     1        one     5
2  foo       two     2        one     4
3  foo       two     2        one     5
4  bar       one     3        one     6
5  bar       one     3        two     7

## Arguments for `pandas.merge`

| Argument      | Description                                                                 | Example (Python) |
|---------------|-----------------------------------------------------------------------------|------------------|
| `left`        | DataFrame to be merged on the left side                                     | `pd.merge(df1, df2, ...)` |
| `right`       | DataFrame to be merged on the right side                                    | `pd.merge(df1, df2, ...)` |
| `how`         | Type of join: `"inner"`, `"outer"`, `"left"`, `"right"`; defaults to `"inner"` | `pd.merge(df1, df2, how="outer")` |
| `on`          | Column names to join on; must exist in both DataFrames. If not specified, uses intersection of column names | `pd.merge(df1, df2, on="id")` |
| `left_on`     | Column(s) in left DataFrame to use as join keys                             | `pd.merge(df1, df2, left_on="id1", right_on="id2")` |
| `right_on`    | Column(s) in right DataFrame to use as join keys                            | Same as above |
| `left_index`  | Use row index in left as join key (supports MultiIndex)                     | `pd.merge(df1, df2, left_index=True, right_on="id")` |
| `right_index` | Use row index in right as join key                                          | `pd.merge(df1, df2, right_index=True, left_on="id")` |
| `sort`        | Sort merged data lexicographically by join keys; default `False`            | `pd.merge(df1, df2, on="id", sort=True)` |
| `suffixes`    | Tuple of suffixes for overlapping column names; default `("_x","_y")`       | `pd.merge(df1, df2, on="id", suffixes=("_left","_right"))` |
| `copy`        | If `False`, avoid copying data in some cases; default always copies         | `pd.merge(df1, df2, copy=False)` |
| `validate`    | Verifies merge type: `"1:1"`, `"1:m"`, `"m:1"`, `"m:m"`                     | `pd.merge(df1, df2, on="id", validate="1:1")` |
| `indicator`   | Adds `_merge` column showing source of each row: `"left_only"`, `"right_only"`, `"both"` | `pd.merge(df1, df2, on="id", indicator=True)` |

Merging on Index

In [88]:
left1=pd.DataFrame({
    "key":list("abaabc"),
    "value":pd.Series(range(6),dtype="Int64")
})

In [89]:
right1=pd.DataFrame({
    "group_val":[3.5,7]
},
                    index=["a","b"])

In [90]:
left1

  key  value
0   a      0
1   b      1
2   a      2
3   a      3
4   b      4
5   c      5

In [91]:
right1

   group_val
a        3.5
b        7.0

In [94]:
pd.merge(left1,right1,left_on="key",right_index=True)

  key  value  group_val
0   a      0        3.5
1   b      1        7.0
2   a      2        3.5
3   a      3        3.5
4   b      4        7.0