# 8.1 Hierarchical Indexing

In [2]:
import numpy as np
import pandas as pd

In [3]:
data=pd.Series(np.random.uniform(size=9),
               index=[['a','a','a','b','b','c','c','d','d'],
                      [1,2,3,1,3,1,2,2,3]])

In [4]:
data

a  1    0.842883
   2    0.931671
   3    0.063081
b  1    0.653360
   3    0.038819
c  1    0.024573
   2    0.937900
d  2    0.396743
   3    0.144168
dtype: float64

In [5]:
data.index

MultiIndex([('a', 1),
            ('a', 2),
            ('a', 3),
            ('b', 1),
            ('b', 3),
            ('c', 1),
            ('c', 2),
            ('d', 2),
            ('d', 3)],
           )

In [6]:
data["b"]

1    0.653360
3    0.038819
dtype: float64

In [7]:
data["b":"c"]

b  1    0.653360
   3    0.038819
c  1    0.024573
   2    0.937900
dtype: float64

In [8]:
data.loc[["b","d"]]

b  1    0.653360
   3    0.038819
d  2    0.396743
   3    0.144168
dtype: float64

In [9]:
data.loc[:,2]

a    0.931671
c    0.937900
d    0.396743
dtype: float64

In [10]:
pd.DataFrame(data)

            0
a 1  0.842883
  2  0.931671
  3  0.063081
b 1  0.653360
  3  0.038819
c 1  0.024573
  2  0.937900
d 2  0.396743
  3  0.144168

In [11]:
data.unstack()

          1         2         3
a  0.842883  0.931671  0.063081
b  0.653360       NaN  0.038819
c  0.024573  0.937900       NaN
d       NaN  0.396743  0.144168

In [12]:
data.unstack().stack()

a  1    0.842883
   2    0.931671
   3    0.063081
b  1    0.653360
   3    0.038819
c  1    0.024573
   2    0.937900
d  2    0.396743
   3    0.144168
dtype: float64

In [13]:
frame=pd.DataFrame(np.arange(12).reshape((4,3)),
                   index=[["a","a","b","b"],
                          [1,2,1,2]],
                   columns=[["Ohio","Ohio","Colorado"],
                            ["Green","Red","Green"]])

In [14]:
frame

     Ohio     Colorado
    Green Red    Green
a 1     0   1        2
  2     3   4        5
b 1     6   7        8
  2     9  10       11

In [15]:
frame.index.names=["key1","key2"]

In [16]:
frame.columns.names=["state","color"]

In [17]:
frame

state      Ohio     Colorado
color     Green Red    Green
key1 key2
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

In [18]:
frame.index.nlevels

2

In [19]:
frame["Ohio"]

color      Green  Red
key1 key2
a    1         0    1
     2         3    4
b    1         6    7
     2         9   10

In [20]:
pd.MultiIndex.from_arrays(
    [["Ohio","Ohio","Colorado"],
     ["Green","Red","Green"]],
    names=["state","color"]
)

MultiIndex([(    'Ohio', 'Green'),
            (    'Ohio',   'Red'),
            ('Colorado', 'Green')],
           names=['state', 'color'])

Reordering and Sorting Levels

In [21]:
frame.swaplevel("key1","key2")

state      Ohio     Colorado
color     Green Red    Green
key2 key1
1    a        0   1        2
2    a        3   4        5
1    b        6   7        8
2    b        9  10       11

In [22]:
frame.sort_index(level=1)

state      Ohio     Colorado
color     Green Red    Green
key1 key2
a    1        0   1        2
b    1        6   7        8
a    2        3   4        5
b    2        9  10       11

In [23]:
frame.swaplevel(0,1).sort_index(level=0)

state      Ohio     Colorado
color     Green Red    Green
key2 key1
1    a        0   1        2
     b        6   7        8
2    a        3   4        5
     b        9  10       11

Summary Statistics by Level

In [24]:
frame.groupby(level="key2").sum()

state  Ohio     Colorado
color Green Red    Green
key2
1         6   8       10
2        12  14       16

In [26]:
frame

state      Ohio     Colorado
color     Green Red    Green
key1 key2
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

In [28]:
frame.groupby(level="color",axis="columns").sum()

C:\Users\Prathamesh Gawas\AppData\Local\Temp\ipykernel_29356\3295922660.py:1: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  frame.groupby(level="color",axis="columns").sum()

color      Green  Red
key1 key2
a    1         2    1
     2         8    4
b    1        14    7
     2        20   10

Indexing with a DataFrame’s columns

In [29]:
frame = pd.DataFrame({"a": range(7), "b": range(7, 0, -1),
                         "c": ["one", "one", "one", "two", "two",
                           "two", "two"],
                      "d": [0, 1, 2, 0, 1, 2, 3]})

In [30]:
frame

   a  b    c  d
0  0  7  one  0
1  1  6  one  1
2  2  5  one  2
3  3  4  two  0
4  4  3  two  1
5  5  2  two  2
6  6  1  two  3

In [31]:
frame2=frame.set_index(["c","d"])

In [32]:
frame2

       a  b
c   d
one 0  0  7
    1  1  6
    2  2  5
two 0  3  4
    1  4  3
    2  5  2
    3  6  1

In [33]:
frame.set_index(["c","d"],drop=False)

       a  b    c  d
c   d
one 0  0  7  one  0
    1  1  6  one  1
    2  2  5  one  2
two 0  3  4  two  0
    1  4  3  two  1
    2  5  2  two  2
    3  6  1  two  3

In [34]:
frame2.reset_index()

     c  d  a  b
0  one  0  0  7
1  one  1  1  6
2  one  2  2  5
3  two  0  3  4
4  two  1  4  3
5  two  2  5  2
6  two  3  6  1